### ISSUE TITLE
[BUG] Barotrauma (btserver) path not found

### ISSUE THREAD

**Issue by Andargor** [GameServerManagers/LinuxGSM#3949] opened 2022-08-15 15:31 UTC
## User Story

As a server admin, I want the btserver configuration changed so that btserver can run.

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [btserver]
* **Command:** [Start]
* **LinuxGSM version:** [v22.1.0] Official docker image

## Further Information

The error below occurs due to the game looking for a non-existent directory.

```bash
Exception: Could not find a part of the path '/home/linuxgsm/.local/share/Daedalic Entertainment GmbH/Barotrauma'. (System.IO.DirectoryNotFoundException)
...
```

### Fix
It might be possible to fix this through the lgsm cfg files, but I do not know how. My solution was to manually execute the following in the container, which allowed to start the server:

```bash
cd /home/linuxgsm/.local/share
mkdir "Daedalic Entertainment GmbH"
cd "Daedalic Entertainment GmbH"
ln -s /home/linuxgsm/serverfiles/ Barotrauma
```

## To Reproduce

Steps to reproduce the behaviour:
1. Try to start the server

## Expected behaviour

That it starts.

EDIT: Corrections

**Comment by h3o66** [comment] 2022-08-15 19:26
Duplicate of #3915

**Closed by h3o66** 2022-08-15 19:26 UTC
Labels: distro: Ubuntu, command: start, info: docker, game: Barotrauma
