### ISSUE TITLE
[BUG] Don't restart server after update (duplicate)

### ISSUE THREAD

**Issue by BlackYuzia** [GameServerManagers/LinuxGSM#2669] opened 2020-01-07 09:21 UTC
@borzaka 
In this update I get the same bug with didn't restart servers like in this issue: #2025 
Issue was closed, but I can't reopen it, so I create this one...

Scripts logs:
> Log with bug:
[csgoserver-script.log](https://github.com/GameServerManagers/LinuxGSM/files/4029768/csgoserver-script.log)
> Log without bug:
[csgoserver-script.log](https://github.com/GameServerManagers/LinuxGSM/files/4029776/csgoserver-script.log)

I can give more logs with the same trouble after today update and without it.
**Just say what logs do u need.**

**Comment by borzaka** [comment] 2020-01-07 20:05
Can you show us your cronjobs? My new guess is that you are running a job at every 5 to 10 minutes, and the update is not able to finish during this time period and therefore the break.

BTW, you should probably use https://github.com/GameServerManagers/LinuxGSM-Support for support, or the Discord channel for asking for help.

**Comment by BlackYuzia** [comment] 2020-01-08 04:28
@borzaka 

> Can you show us your cronjobs?

![image](https://user-images.githubusercontent.com/25010528/71950424-d89f2d80-31df-11ea-910c-14cd3bcdaa93.png)
**On both servers** (where have and didn't have this bug) **crontabs the same.**

> My new guess is that you are running a job at every 5 to 10 minutes, and the update is not able to finish during this time period and therefore the break.

I think what LGSM have check, if update is didn't complete. Didn't do anything. No?

**Comment by borzaka** [comment] 2020-01-10 12:31
In my opinion, you shouldn't monitor your csgoserver in every 5 minutes. No need to. Because they are rarely crashes, and if so, they automatically restart. I haven't setup a monitor command for my community csgoservers. And they are stable.
I'am almost sure, when an update happens, a monitor command kicks in, and starts the server with an unfinished update.

LGSM didn't know that an update is happening. monitor command just sees that a server is not running and starts is.
Correct me, if I'am wrong, but I'am sure, that the 5 minute monitor is unnecessary.

**Comment by dgibbs64** [comment] 2020-01-10 14:16
@borzaka monitor should detect when an update is happening and do nothing. If not then there may be a bug

**Comment by BlackYuzia** [comment] 2020-01-10 15:08
> if so, they automatically restart.

two words about "always auto restart".
Is not true. I get second time trouble, when server just freeze and don't restart. 

**So, how I think, monitor functin is need**. But ... maybe delay should be 10 min or more...
~~SETUP IT TO 1 MIN~~

**Comment by borzaka** [comment] 2020-01-11 11:13
In my experience when a csgoserver crashes (segmentation fault for example), it auto restarts, and sometimes crashes again :) So it can stuck in restart loops. This can be because some update broke the games 3rd party plugins. Only way to fix this is to update the plugins, or disable them
Yes, probably it can freeze too for good.

If someone interested, this is my cronjobs for a csgoserver:
```
# #Counter-Strike: Global Offensive
@reboot su - csgoserver -c '/home/csgoserver/csgoserver monitor' > /dev/null 2>&1
30 3 * * * su - csgoserver -c '/home/csgoserver/csgoserver update' > /dev/null 2>&1
0 0 * * 0 su - csgoserver -c '/home/csgoserver/csgoserver update-functions' > /dev/null 2>&1
```

I don't use monitor frequently, because I'am afraid that if a monitor checks my instance, it will find that it's not running and tries to start it:
- during updates
- sometimes I have slow map changes, during this 1-2 minutes my server became unresponsive

**Comment by CrazyHackGUT** [comment] 2020-01-11 13:21
@borzaka you can't open crontab for your user or what?)
If you like executing commands as `root` user, you should discover optional argument `-user` for crontab command. https://linux.die.net/man/1/crontab or `man crontab` in shell.

**Comment by borzaka** [comment] 2020-01-11 13:29
I have multiple game modes separated into different users, so it's easier to my me to handle the cronjobs in one place.
I got this from the official docs:
https://docs.linuxgsm.com/configuration/cronjobs#real-life-multiple-servers-example

How should I change my cronjobs according to your recommendation?

**Comment by BlackYuzia** [comment] 2020-01-30 05:26
@borzaka @dgibbs64 today (01/29) csgo has been update.

How we can see, do not all servers get fully update. (actualy - restart)
![2020-01-30_071943](https://user-images.githubusercontent.com/25010528/73422419-97f38980-4331-11ea-9469-be71bde5688f.png)
If we try check update by command: `./csgoserver u`
We get message about already up to date:
![image](https://user-images.githubusercontent.com/25010528/73422451-b22d6780-4331-11ea-9cfb-e223decf01eb.png)
after restart server, version was changed.

This is Bug with a monitor? :thinking:

**Comment by BlackYuzia** [comment] 2020-01-30 05:35
After restart all servers (execute selected, he didn't update, I get different version of current build... maybe my fail) version of build was changed:
![image](https://user-images.githubusercontent.com/25010528/73422895-1997e700-4333-11ea-9d33-d9cd25d385f7.png)

**Comment by dgibbs64** [comment] 2020-03-10 16:40
@BlackYuzia looking at your logs in issue #2700 I think you may not be running the latest version of LinuxGSM for one for your servers that are having an issue. Please can you make sure your servers are fully up to date `./csgoserver update-lgsm`.

**Comment by BlackYuzia** [comment] 2020-03-10 16:44
Okey. I check (and update) all servers to latest (LGSM) vesrion.
Then, on update I will feedback again.

**Comment by dgibbs64** [comment] 2020-03-10 16:47
@BlackYuzia thanks. I am unsure if that will help. But I am also not sure how best to resolve this problem.

It appears to me that the issue is that an update fails to complete but is reporting to LinuxGSM that it has updated. Meaning that when the update checks again it thinks the server has updated when it hasnt.

**Comment by dgibbs64** [comment] 2020-07-29 13:40
Work has been done on resolving issues with updating for multiple instances. This should hopefully be resolved now

**Closed by dgibbs64** 2020-07-29 13:40 UTC
Labels: type: bug
