### ISSUE TITLE
gamelogdir has to be reworked

### ISSUE THREAD

**Issue by marvinlehmann** [GameServerManagers/LinuxGSM#1327] opened 2017-02-20 14:35 UTC
Many servers have ` gamelogdir="${rootdir}/log/server"` which isn't really desired, is it? (unnecessary symbolic linkception). Just [search for gamelogdir="${rootdir}/log/server"](https://github.com/GameServerManagers/LinuxGSM/search?utf8=%E2%9C%93&q=gamelogdir%3D%22%24%7Brootdir%7D%2Flog%2Fserver%22&type=Code) to find some of them. (also mumble?)

Furthermore the server log should be set to the correct file (e.g. Hurtworld just uses "gamelog.txt" currently; Teeworlds is misconfigured; ..).

Moreover "gamelogfile" which doesn't even exist (?) is used in the following check: [logs.sh#L20](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/logs.sh#L20)
I guess it should have been "gamelogdir"?

**Comment by UltimateByte** [comment] 2017-02-20 15:51
You're right, I felt there was something wrong when working on gamelogdir which is useful to some games, but appeared to be unnecessary for others. This needs an overhaul revision.

I didn't remember Hurtworld having a fixed log name, this needs to be addressed. Thanks for pointing this out.

As for `-n "${gamelogfile}` , here https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/logs.sh#L20 this was a bit messy and is now a legacy function. Rust didn't have a custom log location, so it was into serverfiles by default, and had to be moved into gamelogdir upon server start, and Rust log was set within ${gamelogdate} var which didn't include ${gamelogdir}. For some reason, I added ${gamelog} to Rust which wasn't used, so this cleanup code specific to Rust worked as intended.
I did the revision for Rust that now supports custom logdir.  It's more simple to look at the commit to understand: https://github.com/GameServerManagers/LinuxGSM/commit/92f748c1ca47cad2b120572c5d44402bc0c02af5#diff-34f056db9e8692880a2f240fa083de4c
It is now set with ${gamelogdate} like any other server that allows custom log location/file.

**Comment by UltimateByte** [comment] 2017-02-20 16:43
Seing [this](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_logs.sh#L34), it looks like `gamelogdir` something is wrong in variables management.

Here is how i think it should be:
`gamelogdir` would only exist if game server has default logs OR we can set custom log location. In any case, `gamelogdir="${rootdir}/log/server"`.
Then another variable would be required for default server logs that we cannot change, like `defaultgamelogdir`.
Then symlink would be: 

```bash
if [ -n "${defaultgamelogdir}" ]; then
	if [ ! h "${gamelogdir}" ]; then
		ln -nfsv "${defaultgamelogdir}" "${gamelogdir}"
	fi
fi
```

And `gamelogdir` creation would be:
```bash
if [ -n "${gamelogdir}" &&[ ! -d "${gamelogdir}" ]]&&[ -z "${defaultgamelogdir}"  ]; then
	mkdir -pv "${gamelogdir}"
fi
```

**Comment by dgibbs64** [comment] 2017-05-15 20:19
My current solution required no extra vars

```
# unless gamelogdir is within logdir
# e.g serverfiles/log is not within log/: symlink created
# log/server is in log/: symlink not created
if [ -n "${gamelogdir}" ]; then
	if [ "${gamelogdir:0:${#logdir}}" != "${logdir}" ];then
		ln -nfsv "${gamelogdir}" "${logdir}/server"
	fi
fi
```

**Comment by dgibbs64** [comment] 2017-06-20 19:22
This issue was resolved in the latest release

**Closed** 2017-06-20 19:22 UTC
Labels: bug, enhancement
