### ISSUE TITLE
appid not being forwarded to the command_validate script from the "main menu"

### ISSUE THREAD

**Issue by draakuns** [GameServerManagers/LinuxGSM#1893] opened 2018-05-04 17:33 UTC
Hi,

I just noticed (but I really don't know where it started or whether I am doing something wrong) that command_validate.sh function gets an empty string for "appid" variable, which should be provided from _default.cfg file as far as I can see. 

the main command is:
` ${unbuffer} ./steamcmd.sh +login "${steamuser}" "${steampass}" +force_install_dir "${serverfiles}" +app_update "${appid}" ${branch} validate +quit | tee -a "${lgsmlog}"`

which debugging gets:
`./steamcmd.sh +login myuser mypassword +force_install_dir /home/steamsrv/arma3/serverfiles +app_update '' validate +quit
`
I tried too with my insurgency server and I get the same result.
So the validation is never done for the desired appid.

Best regards,
Draakuns.

**Comment by UltimateByte** [comment] 2018-05-05 00:11
Hi,

Rule N°1) Read rules

https://linuxgsm.com/support/#guide

I see no reason why this would be a global LinuxGSM issue, so closing for now.

**Comment by draakuns** [comment] 2018-05-07 08:07
Well, I don't understand your statement, as I am trying to issue a problem in your global bash scripts. If I explain that the appid is lost somewhere in the execution of both servers (arma3 and insurgency), then the problem *should* rely on the LGSM layer.
I will add the info about OS whenever possible.

**Comment by draakuns** [comment] 2018-05-07 08:18
Gameserver: As I already wrote, Arma3 & Insurgency, which fail in the same way.

Postdetails: https://pastebin.com/xwB3mxe4

**Comment by draakuns** [comment] 2018-05-07 08:36
exec dev-debug-function-order.log: https://pastebin.com/NbsHeHxp

exec dev-debug.log: https://pastebin.com/nFmM1AzX

Let me know if need anything else.

**Comment by UltimateByte** [comment] 2018-05-07 22:29
Confirmed. For once it's not a false alert, thanks for reporting.

Sample log:

```
ultimatebyte@gaben:~/serverfiles/insurgency$ rm insurgency_sound_003.vpk insurgency_sound_004.vpk
ultimatebyte@gaben:~/serverfiles/insurgency$ cd
ultimatebyte@gaben:~$ ./insserver v
[ .... ] Validate insserver: Validating files: SteamCMD
        * Validating may overwrite some customised files.
        * https://developer.valvesoftware.com/wiki/SteamCMD#Validate
Redirecting stderr to '/home/ultimatebyte/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
[  OK  ] Validate insserver: Validating files: SteamCMD
```

Checking deeper to diagnose this.

**Comment by UltimateByte** [comment] 2018-05-07 22:50
This is to blame.
https://github.com/GameServerManagers/LinuxGSM/commit/26b717b0f80795a6a45bf1b0fb48c1beda662e2c#diff-44346d483951ed5dfa13b6f06008a3a0
Not sure why it's here yet but that's the issue. It rewrites appid with an unset variable.

**Comment by UltimateByte** [comment] 2018-05-07 23:17
Fixed.

Thanks a lot for sharing your details after my 1st post and congrats for not being discouraged.
Please update your linuxgsm with `./gameserver ul` to check if it resolved the issue for you as well.

Cheers 🍻

**Closed by UltimateByte** 2018-05-07 23:17 UTC
Labels: Outcome: issue resolved, Platform: LinuxGSM, Type: bug

**Comment by draakuns** [comment] 2018-05-08 09:08
Hey!

I did the explanation manually instead of PD because it felt more clear, but maybe it wasnt :)

To me, it seems it was a separate function beeing feeded arguments from commandline, and at some point it was merged into your main... Who knows? 
Also, IMO there's some guilt to blame to steamcmd for not parsing well things, or complaining about the lack of appid on their validation...

It is fixed on both servers I have ;)

Happy to hear that it has been fixed so quickly, thanks!

Dont worry about the 1st post... I can understand the monster that sometimes approaches in the form of an issue from inexpert hands... Its always good to have guidelines for all of us.

BR
Draakuns

**Comment by UltimateByte** [comment] 2018-05-08 17:40
Thanks for the feedback! Glad it was just that to fix :p 

I believe it was just a programming mistake because I've never seen the appid being passed as a function argument. Maybe it was in the process of making a universal installer, which is an idea we had for some time now.

Yes, we have so many unhelpful posts with isolated issues that it's sometimes harder to notice when it's a global one at first glance. When experiencing a bug, postdetails is the bare minimum info to provide, and you went further with dev-debug outputs which gained me some time: with functions order, we know where to look, with the log I was able to see that appid was set to an empty var at some point :)

**Comment by draakuns** [comment] 2018-05-09 08:11
Happy to hear. 100% sure you will hear again from me ;)

Good job you did here!
Draakuns
