### ISSUE TITLE
[Server Request] Avorion

### ISSUE THREAD

**Issue by spannerman79** [GameServerManagers/LinuxGSM#1287] opened 2017-02-01 18:38 UTC
http://wiki.avorion.net/index.php?title=Setting_up_a_server#Starting_the_server_.28Linux.29
SteamCMD app ID `565060`

No rush or expectations on ETA

**Comment by marvinl97** [comment] 2017-02-01 19:58
Duplicate of #1271

**Closed by marvinl97** 2017-02-01 19:58 UTC
Labels: outcome: duplicate, type: game server request, game: Avorion, engine: avorion
