### ISSUE TITLE
Send alert problem 

### ISSUE THREAD

**Issue by DobriyDed** [GameServerManagers/LinuxGSM#1562] opened 2017-08-03 15:18 UTC
Ubuntu server 16.04.2 LTS x86_64 Kernel 4.4.0.87 tmux 2.1 Glibc 2.23 Project zomboid server appid 380870
--------------------not-so-exact output due to translation-------------
```
./pzserver ta 
[ .... ] Alert pzserver: Sending alert: xxxxxxx@xxxxxx.comtail: read error '/home/pzserver/Zomboid/Logs/logs_01_08' - this is directory
tail: read error '/home/pzserver/Zomboid/Logs/logs_02_08' - this is directory
tail: read error '/home/pzserver/Zomboid/Logs/logs_03_08' - this is directory
mail:cannot send message: process finished........ 
```
-------------------------------------
and    /home/pzserver/Zomboid/Logs/logs_0*_08  yup, its directories.
what I'm doing wrong?

**Comment by marvinlehmann** [comment] 2017-08-03 15:34
Probably #957 :/

**Comment by dgibbs64** [comment] 2018-07-21 16:11
Duplicate of #957
closing

**Closed by dgibbs64** 2018-07-21 16:11 UTC
Labels: outcome: duplicate, game: Project Zomboid, engine: projectzomboid
