### ISSUE TITLE
[BUG] Server Description Missing.

### ISSUE THREAD

**Issue by pureche** [GameServerManagers/LinuxGSM#3355] opened 2021-03-11 07:28 UTC
## User Story

As a server host, I want to be able to set a static server description for Rust servers so that I can set a server description.

## Basic info

* **Distro:** [CentOS 7.9]
* **Game:** [Rust]
* **Command:** [Wipe]
* **LinuxGSM version:** [v21.1.3]

## Further Information

It's similar to #1976 but in a different way. 

I'm using LinuxGSM to install a Rust game server, but the description for the game server is missing. i.e. server.description property. 

Supposedly, according to `/home/rustserver/serverfiles/server/rustserver/cfg/server.cfg`(It's a bash file where it "Creates default server configs") , it downloads the config file from `https://github.com/GameServerManagers/Game-Server-Configs/blob/master/Rust/server.cfg`, but I can't find the exact file anywhere. The only thing I have for the same functionality/content of that config file is a `serverauto.cfg` file in `/home/rustserver/serverfiles/server/rustserver/cfg,` where it doesn't have a `server.description` property, nor does it look anything like the `server.cfg` file hosted on github.

From the name,`serverauto.cfg`, I inferred that the file was auto generated, and for every time I use the `wipe` command, this file gets reset. So even if I manually add `server.description` to `serverauto.cfg`, it'll still get overwritten on `wipe`. 

If anyone could let me know how I can load the `server.cfg` file properly without having to manually set `server.description` each wipe I'd really appreciate it.

## To Reproduce

Steps to reproduce the behaviour:
1. Run ./rustserver wipe or full-wipe
2. The server.cfg file gets overwritten by default stuff, and does not download the Game-Server-Configs file.

## Expected behaviour

It should download the config file from github based on Rust game. 

## Edits
Edit1:

I was reading rustserver-console.log and found these entries:

`-e "creating ${servercfgdir} config directory." 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

-e "" 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

-e "${lightyellow}Downloading ${gamename} Configs${default}" 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

-e "=================================" 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

-e "default configs from https://github.com/GameServerManagers/Game-Server-Configs" 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

-e "copying ${config} config file." 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

-e "copying ${servercfgdefault} config file." 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

-e "changing hostname." 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

-e "changing rcon/admin password." 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

-e "Config file not found, cannot alter it." 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)`

So it's clearly something is wrong. I'm just not sure what is the reason why it's not finding the config file.

**Comment by h3o66** [comment] 2021-03-11 19:42
Maybe I do not understand what you want to say, but the config file `serverfiles/server/rustserver/cfg/server.cfg` does not get deleted for me with the wipe command.
The config ONLY gets downloaded when you install the server, there is no point for me why the script should download it within a wipe.

**Comment by pureche** [comment] 2021-03-11 19:55
> Maybe I do not understand what you want to say, but the config file `serverfiles/server/rustserver/cfg/server.cfg` does not get deleted for me with the wipe command.
> The config ONLY gets downloaded when you install the server, there is no point for me why the script should download it within a wipe.

Yeah, it's kind of confusing. Basically my problem is that I don't have a config file from https://github.com/GameServerManagers/Game-Server-Configs for some reason. 

the `serverfiles/server/rustserver/cfg/server.cfg` contains bash file information, I'll copy a snippet of it:

`#!/bin/bash
# LinuxGSM install_config.sh module
# Author: Daniel Gibbs
# Contributors: http://linuxgsm.com/contrib
# Website: https://linuxgsm.com
# Description: Creates default server configs.

functionselfname="$(basename "$(readlink -f "${BASH_SOURCE[0]}")")"

# Checks if server cfg dir exists, creates it if it doesn't.
fn_check_cfgdir(){
	if [ ! -d "${servercfgdir}" ]; then
		echo -e "creating ${servercfgdir} config directory."
		fn_script_log_info "creating ${servercfgdir} config directory."
		mkdir -pv "${servercfgdir}"
	fi
}

# Downloads default configs from Game-Server-Configs repo to lgsm/config-default.
fn_fetch_default_config(){
	echo -e ""
	echo -e "${lightyellow}Downloading ${gamename} Configs${default}"
	echo -e "================================="
	echo -e "default configs from https://github.com/GameServerManagers/Game-Server-Configs"
	fn_sleep_time
	mkdir -p "${lgsmdir}/config-default/config-game"
	githuburl="https://raw.githubusercontent.com/GameServerManagers/Game-Server-Configs/master"
	for config in "${array_configs[@]}"; do
		fn_fetch_file "${githuburl}/${gamedirname}/${config}" "${remote_fileurl_backup}" "GitHub" "Bitbucket" "${lgsmdir}/config-default/config-game" "${config}" "nochmodx" "norun" "forcedl" "nomd5"
	done
}`

So as you can see it's not an actual server.cfg file. Something somewhere went wrong, and I don't know what it is. 

And you are right, it should've been downloaded when I install the server, but I don't know what's going on here.

**Comment by h3o66** [comment] 2021-03-11 20:04
remove this file and execute again the lgsm install command
in this case: `./rustserver install` or `./rustserver auto-install`

PS: also formatted your comment the right way ;)

**Comment by pureche** [comment] 2021-03-11 20:08
> remove this file and execute again the lgsm install command
> in this case: `./rustserver install` or `./rustserver auto-install`
> 
> PS: also formatted your comment the right way ;)

Running `./rustserver install` will replace all my files and settings in lgsm, right? Reason I'm asking is because I already have the server setup and running with oxide plugins, and user groups and stuff. 

I had trouble installing it online because of the routing issue of my server(that has a huge latency connecting to github/bitbucket). I asked on discord to see if I can install it somewhat offline/locally, but didn't get a response.

**Comment by h3o66** [comment] 2021-03-11 20:32
well, then replace the config manually or backup the important data and reinstall.
Just tested a manual install, that worked.

**Comment by pureche** [comment] 2021-03-11 21:29
> well, then replace the config manually or backup the important data and reinstall.
> Just tested a manual install, that worked.

What do you mean by manual install? Download the github repo to local and run `./rustserver` install ?

**Comment by h3o66** [comment] 2021-03-14 12:41
well, dont keep it this complicated:

delete or move away the config `serverfiles/server/rustserver/cfg/server.cfg`

then switch to the folder `serverfiles/server/rustserver/cfg/` and just download the template:
`wget https://github.com/GameServerManagers/Game-Server-Configs/raw/master/Rust/server.cfg`

**Comment by pureche** [comment] 2021-03-14 14:03
> well, dont keep it this complicated:
> 
> delete or move away the config `serverfiles/server/rustserver/cfg/server.cfg`
> 
> then switch to the folder `serverfiles/server/rustserver/cfg/` and just download the template:
> `wget https://github.com/GameServerManagers/Game-Server-Configs/raw/master/Rust/server.cfg`

That's what I ended up doing. It seems to be working. I haven't tried to see if wipe/full-wipe is going to cause any issues. But yeah, this is kind of a bug on the program at where the console log says config file missing, it should've downloaded the Game-Server-Configs, but it didn't.

**Comment by h3o66** [comment] 2021-03-14 15:04
I could not reproduce this with a fresh install of the gameserver.

~ closing as solved

**Closed by h3o66** 2021-03-14 15:04 UTC
Labels: command: wipe, distro: CentOS, game: Rust, type: support
