### ISSUE TITLE
Unreal Tournament 99 OldUnreal patch

### ISSUE THREAD

**Issue by bmunger** [GameServerManagers/LinuxGSM#3099] opened 2020-11-11 18:15 UTC
## What game server would you like adding?

UT99 - OldUnreal patch

## Can you link to any tutorials or guides?

Currently, the UTPG 451 patch is used for the dedicated server.  Recently, OldUnreal has been given permission to continue patching the game.  It may be best to follow those releases.

https://github.com/OldUnreal/UnrealTournamentPatches

## Is the server on Steam?

* [ ] Yes
* [X] No

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [X] Yes
* [ ] No

**Comment by kvbev** [comment] 2020-11-13 02:37
This update is being tracked here.
https://github.com/GameServerManagers/LinuxGSM/issues/2961

**Comment by dgibbs64** [comment] 2020-11-13 21:55
Duplicate of #2961

**Closed by dgibbs64** 2020-11-13 21:55 UTC
