### ISSUE TITLE
TS3 Backup: lock file not removed after backup

### ISSUE THREAD

**Issue by master2die** [GameServerManagers/LinuxGSM#1189] opened 2016-11-17 23:59 UTC
Hey there,

the lock file is not removed after a successful backup of ts3. happens on several systems :/

Looking forward for a fix!

Best regards

Additional Info about the Script / Editing:

I run this in Debian 8 (based on LXC Containers), with no changes made to the software. Just entered my pushbullet api key and created the cronjobs. I made everything according to the documentation.

**Comment by UltimateByte** [comment] 2016-11-18 10:47
Hi. I cannot reproduce the issue on a regular Debian 8. So my guess is that something is happening with your LXC container. Once again, LGSM is untested for containers. If you can think of a modification to the code that would solve your issue while keeping the same behavior for others, feel free to share your ideas.

```
ultimatebyte@game:~$ ./mumbleserver b
    fetching command_backup.sh...OK
    fetching check_system_dir.sh...OK
    fetching check_logs.sh...OK
[  OK  ] Backup mumble-server: Backup starting
[ INFO ] Backup mumble-server: There are no previous backups
    fetching check_status.sh...OK
    fetching info_config.sh...OK
[  OK  ] Backup mumble-server: Completed: mumble-server-2016-11-18-114534.tar.gz, total size 36M
ultimatebyte@game:~$ ./mumbleserver b
[  OK  ] Backup mumble-server: Backup starting
        * Previous backup was created less than 1 day ago, total size 36M
[  OK  ] Backup mumble-server: Completed: mumble-server-2016-11-18-114544.tar.gz, total size 36M

```

**Comment by master2die** [comment] 2016-11-18 11:16
Just check my KVM machine, same error there too :/

**Comment by UltimateByte** [comment] 2016-11-18 11:18
What is your main script version ?
Possible reason could be that you're missing backup variables and it messes up with the process.
Also, did you run a an `uf` command first ?

**Comment by master2die** [comment] 2016-11-18 11:25
hey there,

where do I see the main version? I just executed the inbuild postdetails: http://hastebin.com/ofeqijadoq

I do uf every single night as cronjob, as addition to backup and update itself.

**Comment by master2die** [comment] 2016-11-18 11:28
Shame onto my head! I had missing dependencies. Thank you so much for your help!

**Comment by UltimateByte** [comment] 2016-11-18 11:29
Missing bzip2 ? Haha.

**Comment by master2die** [comment] 2016-11-18 11:35
Nah, I figured out this just fixed the issue on the KVM system (where I missed it), but the LXC containers are not working - with correct architecture and dependencies correctly installed. Meh :/

**Comment by UltimateByte** [comment] 2016-11-18 11:52
`find: missing argument to `-mtime'` is due to something broken when you're using an outdated lgsm main script.
I  think i need to make a conditional check for maxbackupdays for better retrocompatibility. However, i tested it, and it makes no issue other than this displayed error because of an empty variable.

It has something to do with the fact that you got updateonstart activated.

I need to rethink this thing to solve those two issues.

**Comment by master2die** [comment] 2016-11-18 12:01
Yeah, for now I disabled it. If teamspeak servers are outdated for a few hours it is not critical, since I do the update cronjob every night though.

Thanks man! If you like, send me a mail to master2die [at] scs-simulatoren [dot] de with your paypal and I will send some bucks for your help! :-)

**Comment by UltimateByte** [comment] 2016-11-18 12:15
Thanks man. If you wish to donate for my community, you can do so here: https://www.terageek.org/donation/ (use "Montant Libre" to input whatever amount you want).

So i got it fixed for updateonstart in "hotfixes" branch. 
I also fixed the -mtime issue.
Will pull-request it, should be fixed soon with an uf. :)

**Comment by UltimateByte** [comment] 2016-11-18 12:20
If you're using backups a lot, you should really update your main scripts. It provides three very useful settings introduced with the last major update: 

```
## Backup | https://github.com/GameServerManagers/LinuxGSM/wiki/Backup
maxbackups="4"
maxbackupdays="30"
stoponbackup="on"
```

**Closed** 2016-11-18 12:53 UTC
Labels: bug, development queue

**Comment by UltimateByte** [comment] 2016-11-18 13:04
Commited to master. Please, tell me if it's solved for you after an uf.

**Comment by master2die** [comment] 2016-11-18 13:16
Works! :)

**Comment by UltimateByte** [comment] 2016-11-18 13:20
Thanks, have fun !

PS: You mentioned donating to me, but you can also donate to Daniel Gibbs, creator and main dev of LGSM: https://gameservermanagers.com/donate/
