### ISSUE TITLE
[Server Request]: Trackmania

### ISSUE THREAD

**Issue by BestNoob** [GameServerManagers/LinuxGSM#4660] opened 2024-09-23 16:23 UTC
### Game server

Trackmania 2020

### Linux support

- [X] Yes

### Steam

No

### Steam appid

2225070

### Guides

Trackmania (2020) https://wiki.trackmania.io/en/dedicated-server/Setup/Linux
Maniaplanet (TM2) https://doc.maniaplanet.com/dedicated-server/getting-started
Trackmania Forever (2008 TMNF, TMUF) https://server.xaseco.org/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by h3o66** [comment] 2024-09-23 19:30
Duplicate of #1444  

tm2020 #4027 

for tm nf / uf I have already a Pr up, what in general works, but it is not finished yet. see  #4184

**Closed by h3o66** 2024-09-23 19:30 UTC
Labels: type: game server request

**Comment by BestNoob** [comment] 2024-11-27 19:39
Its not directly an duplicate, there are DIFFERENT versions of this game TM202 is the recent one, but old ones still played by the community and working.

TMNF/TMUF = Trackmania Nations Forever
TM2 / MP4 = Trackmania 2 - Maniaplanet
Trackmania Turbo (no real dedicated servers)
TM2020 = Trackmania 2020 <----- recent one playable on ALL PLATFORMS (STEAM, EPIC, Ubisoft, Nintendo; Playstation , Xbox ....)

**Comment by h3o66** [comment] 2024-11-27 20:29
> TM2020 = Trackmania 2020 <----- recent one playable on ALL PLATFORMS (STEAM, EPIC, Ubisoft, Nintendo; Playstation , Xbox ....)

yes, but custom servers not joinable from other then pc, as there is a limitationon client and platform side.
No clue as well where you got the info for Nintendo.
I do not even see something on the offical website.

**Comment by BestNoob** [comment] 2024-11-28 08:47
> > TM2020 = Trackmania 2020 <----- recent one playable on ALL PLATFORMS (STEAM, EPIC, Ubisoft, Nintendo; Playstation , Xbox ....)
> 
> yes, but custom servers not joinable from other then pc, as there is a limitationon client and platform side. No clue as well where you got the info for Nintendo. I do not even see something on the offical website.

my mistake TM (TMNF/TMUF) was playable on Wii/WiiU, Turbo on DS but TM2020 is only playable via Emulation/MOD

I can create a map on my PS4 and play it via PC but i cannot edit it on my PC than the game tells me to do that on my .. console ...

TM (2020) Servers are platform independent
https://www.ubisoft.com/en-us/help/trackmania/gameplay/article/crossplay-in-trackmania/000104646

Progression seems to be shared with the linked ubisoft account
https://www.ubisoft.com/en-gb/help/trackmania/connectivity-and-performance/article/cross-platform-content-sharing-in-trackmania/000104648

Some OLDER TUTORIALS are gone (dont tell ppl. lies like internet will never forget smth.)
But all TM Servers are running on ... LINUX ..... so there is no need to dont add those to LGSM

**Comment by BestNoob** [comment] 2024-11-28 08:52
I dont know if it is related to LINUX Server files but with WINDOWS DEDICATED Server file IT IS BROKEN !
depending on LOCATION where u download it from you recieve DIFFERENT (broken) files:

ASIA: 155MB
EUROPE: 158MB
USA: 163MB

as the one from the USA Servers is the correct and latest one.

**Comment by h3o66** [comment] 2024-11-28 19:34
> TM (2020) Servers are platform independent [ubisoft.com/en-us/help/trackmania/gameplay/article/crossplay-in-trackmania/000104646](https://www.ubisoft.com/en-us/help/trackmania/gameplay/article/crossplay-in-trackmania/000104646)

Kind of , the club servers that you can create are cross platform, but not the dedicaded servers that you can host yourself.

As well here is a note from a Ubisoft dev, last screen:
![image](https://github.com/user-attachments/assets/4189364f-e762-42a1-bf61-1970136cec74)

https://www.reddit.com/r/TrackMania/comments/xbp777/trackmania_on_consoles_will_not_be_recieving_a/

as well see the comment from there:
https://www.reddit.com/r/TrackMania/comments/xbp777/comment/io3issp/

**Comment by BestNoob** [comment] 2024-11-29 09:53
Ok. But lets go back to the most important point .. ADDING a TM title to LinuxGSM.
