### ISSUE TITLE
[FEATURE] Multithreaded Backups

### ISSUE THREAD

**Issue by russbrucks** [GameServerManagers/LinuxGSM#3945] opened 2022-08-10 21:09 UTC
## User Story

As a server admin, I would like backups to be multithreaded so that they finish in a timely manner.

## Basic info

* **Distro:** [Ubuntu 22.04.1]
* **Game:** [Valheim], [ProjectZomboid], [DayZ], [Minecraft], [Starbound]
* **Command:** [Backup]
* **LinuxGSM version:** [v22.1.0]

## Further Information

As part of the install configuration, can you check if pigz is installed?  The current command_backup.sh script uses the gzip option with tar, which is single threaded.  On my server it makes backups take several minutes for only a few GB.

tar offers the option:   --use-compress-program, which you can then reference pigz there.

Here is the current single threaded code from command_backup.sp, Line 142:

` tar -czf "${backupdir}/${backupname}.tar.gz" -C "${rootdir}" --exclude "${excludedir}" --exclude "${lockdir}/backup.lock" ./.`

By removing the z from -czf, and adding the --use-compress-program, the updated code becomes:

` tar --use-compress-program="pigz -k " -cf "${backupdir}/${backupname}.tar.gz" -C "${rootdir}" --exclude "${excludedir}" --exclude "${lockdir}/backup.lock" ./.`

I've updated the command_backup.sh for all of my game servers to reflect this change, and my backups now only take 20-40 seconds instead of 4 or 5 minutes.  

It would be a very nice quality of life feature if LGSM would check for pigz, and use this multithreaded option when it is available.

## Further Reading

https://stackoverflow.com/questions/36917882/how-to-use-pigz-with-tar
https://www.maketecheasier.com/compress-files-faster-with-pigz/

**Comment by h3o66** [comment] 2022-08-22 14:20
Duplicate of #3422

**Closed by h3o66** 2022-08-22 14:20 UTC
Labels: type: feature request, distro: Ubuntu, command: install, command: backup, command: update, feature

**Comment by russbrucks** [comment] 2022-08-22 15:06
I'm sad that you don't see the merit of increased performance and speed.  But I love what you guys do!  Keep up the great work!!

**Comment by h3o66** [comment] 2022-08-22 15:14
> I'm sad that you don't see the merit of increased performance and speed. But I love what you guys do! Keep up the great work!!

Well, I just closed this as a duplicate issue.
See as well the mentioned issue.
This does not mean that we will not look at this :)

**Comment by Claiyc** [comment] 2022-08-22 15:15
However you need to understand that we have a ton of requests like this. If you are familiar and able to meet our standards, feel free to create a pull request yourself and we'll be happy to merge it.

**Comment by russbrucks** [comment] 2022-08-22 15:27
Thank you all for the quick feedback!  I doubt my scripting skills are up to par to your standards, but I can easily hack the change into my own server scripts.  :D
