### ISSUE TITLE
[BUG] Terraria (Login Failure: Invalid Password FAILED with result code 5)

### ISSUE THREAD

**Issue by mirkoman007** [GameServerManagers/LinuxGSM#1238] opened 2017-01-11 19:17 UTC
I enter correct username and password but I always get:

[----] Update complete, launching Steamcmd...
Redirecting stderr to '/home/terrariaserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

Logging in user 'mirkoman007' to Steam Public...Login Failure: Invalid Password
FAILED with result code 5
ERROR! Failed to request AppInfo update, not online or not logged in to Steam.
Redirecting stderr to '/home/terrariaserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

**Comment by emilekm** [comment] 2017-01-11 20:36
This bug is caused by quotation marks in [this file](https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/install_server_files.sh#L80-L92).
To fix it on your own, simply modify `lgsm/functions/install_server_files.sh`, by removing quatation marks around `${steamuser}` and `${steampass}`.

This is possibly outcome of steamcmd update (not sure, started using it today aswell).

**Comment by UltimateByte** [comment] 2017-01-11 21:03
See also https://github.com/GameServerManagers/LinuxGSM/issues/1203 to understand the issue better.

Ultimately, since it's now fixed for master branch, you can just update your functions.
./terrariaserver uf

Please, let us know if this isn't enough to solve your issue.
I'll close it for now, feel free to feedback and comment again, we will re-open if needed.

**Closed by UltimateByte** 2017-01-11 21:03 UTC
