### ISSUE TITLE
This commit regressed #3764. Enabling monitor on 7 Days to Die continually restarts the server

### ISSUE THREAD

**Issue by VlkaFenryka** [GameServerManagers/LinuxGSM#4615] opened 2024-07-25 07:49 UTC
This commit regressed #3764. Enabling monitor on 7 Days to Die continually restarts the server

_Originally posted by @parasyte in https://github.com/GameServerManagers/LinuxGSM/pull/4510#discussion_r1673145468_

**Comment by parasyte** [comment] 2024-07-29 18:13
Duplicate of #4610.

**Closed** 2024-07-29 21:13 UTC
Labels: game: 7 Days to Die
