### ISSUE TITLE
SDTD Server SteamCmD

### ISSUE THREAD

**Issue by DerMoki** [GameServerManagers/LinuxGSM#2684] opened 2020-02-12 14:40 UTC
Hey

I cant install 7 Days to Die Server, because i have a issue with steamcmd.
My Server Debian 10. 

`Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '294420' state is 0x2 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 2
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '294420' state is 0x2 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 3
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...threadtools.cpp (833) : Assertion Failed: ThreadGetProcessExitC                           ode: no such process 18823
Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '294420' state is 0x2 after update job.
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.
Warning! SteamCMD did not complete the download, retrying: Attempt 4
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '294420' state is 0x2 after update job.
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.
Warning! SteamCMD did not complete the download, retrying: Attempt 5
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...threadtools.cpp (833) : Assertion Failed: ThreadGetProcessExitC                           ode: no such process 19319
Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '294420' state is 0x2 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 6
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '294420' state is 0x2 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 7
Removing
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...threadtools.cpp (833) : Assertion Failed: ThreadGetProcessExitCode: no such process 19808
Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '294420' state is 0x2 after update job.
Warning! SteamCMD did not complete the download, retrying: Attempt 8
Removing
Redirecting stderr to '/home/sdtdserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '294420' state is 0x2 after update job.
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.
Warning! SteamCMD did not complete the download, retrying: Attempt 9
Removing
[ERROR ] Install sdtdserver: SteamCMD is missing
mkdir: created directory '/home/sdtdserver/steamcmd'
extracting steamcmd_linux.tar.gz...OK
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/home/sdtdserver/lgsm/functions/install_server_files.sh: line 118: ./steamcmd.sh: No such file or directory
Warning! SteamCMD did not complete the download, retrying: Attempt 10
Removing
[ERROR ] Install sdtdserver: SteamCMD is missing
mkdir: created directory '/home/sdtdserver/steamcmd'
extracting steamcmd_linux.tar.gz...OK
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/home/sdtdserver/lgsm/functions/install_server_files.sh: line 118: ./steamcmd.sh: No such file or directory
Failure! SteamCMD did not complete the download, too many retrys
`

**Comment by h3o66** [comment] 2020-02-12 16:13
To be sure that the issue is related to lgsm and not something else please add the details of your server. ( Post details in this case )
Where is this server hosted ? ( at home or externally hosted )
Is this a hardware or a vm ?
Do you have enough disk space on the server ?

**Comment by DerMoki** [comment] 2020-02-12 17:40
This is a VM, More than 1TB space empty, 60GB Memory, 10 Core

I hosted over 2 years a sdtd-Server!
After update to SDTD Version1.8 (May 2019 !!) i am unable to update or feshinstall a new server.
I have also a ticket open to valve, here you can see it i am not the only one with timeout problems.
https://github.com/ValveSoftware/steam-for-linux/issues/6692

Last week i updatet the complete Server from Debian 9 to Debian 10, but i have still this Problem with Steam-CMD. I need help :)

**Comment by h3o66** [comment] 2020-02-12 17:52
Be aware that the issue you linked an the output here have a different error in the output.
Before you had a timeout and not a update error.

**Comment by DerMoki** [comment] 2020-02-12 18:31
Yes i see, so i need support for the error in the first post here :)

**Comment by Grimston** [comment] 2020-02-12 23:05
Unfortunately it looks like the local steam CDN server is at fault. 

This issue was noticed for Rust a few years back :[https://gaming.stackexchange.com/questions/321270/error-app-255850-state-is-is-0x2-after-update-job](https://gaming.stackexchange.com/questions/321270/error-app-255850-state-is-is-0x2-after-update-job)

It appears the fix is to just wait for them to sort it out.

**Comment by DerMoki** [comment] 2020-02-13 17:53
"SteamCMD directly without a script" - i have tested, but the Error is the same

**Comment by dgibbs64** [comment] 2020-03-10 15:53
This issue can not be resolved by LinuxGSM is appears to be an issue with steam content distribution. I will close this issue.

**Closed by dgibbs64** 2020-03-10 15:53 UTC
Labels: info: steamcmd
