### ISSUE TITLE
[Rust] Random seed not work

### ISSUE THREAD

**Issue by NordHol** [GameServerManagers/LinuxGSM#2208] opened 2019-02-24 22:31 UTC
I have a problem with random seed generation. After a full wipe, I have the same map generated.
```
seed="" # default random; range : 1 to 2147483647 ; used to change or reproduce a procedural map
salt="" # default random; range : unknown range ; used to recover a known setting from an existing map
worldsize="3500" # default 3000; range : 1000 to 6000 ; map size in meters
saveinterval="300" # Auto-save in seconds
tickrate="30" # default 30; range : 15 to 100
```
In the config I have the default settings. But the map is the same.
What could be the problem? And sorry for my english :(

**Comment by dgibbs64** [comment] 2020-07-21 10:54
I will be working on a random seed generator for the next release

**Comment by dgibbs64** [comment] 2020-09-24 15:07
Duplicate of #2915

**Closed by dgibbs64** 2020-09-24 15:07 UTC
Labels: game: Rust, type: feature request
