### ISSUE TITLE
[Bug]: No log output to disk with Rust server on Ubuntu 22.04 when "rustcarbon" installed

### ISSUE THREAD

**Issue by xibalbus** [GameServerManagers/LinuxGSM#4212] opened 2023-05-24 18:24 UTC
### User story

As a server owner I wish to have rustcarbon installed and still view logs on disk

### Game

Rust

### Linux distro

Ubuntu 22.04

### Command

command: start

### Further information

Whenever I install "rustcarbon" using mods-install and then start the server, I stop getting log entries to log/console/rustserver-console.log.

`cat log/console/rustserver-console.log`

The above command returns an empty log.
Also applies to Debian, 9, 10, 11 and Ubuntu 20.04 and centos, Rocky

When manually setting the -logfile in rustserver.cfg via startparameters, it works.

**Comment by KissmanCZ** [comment] 2023-05-24 20:22
exactly same here.... Ubuntu 22 Server Edition

**Comment by dgibbs64** [comment] 2023-09-01 21:13
The logs output come from the tmux session output. In other words whatever the game server outputs gets logged. It is likely that Carbon itself is preventing the server from outputting the logs.

**Comment by ervins0x** [comment] 2023-09-10 09:21
Same here, seems related:
https://github.com/GameServerManagers/LinuxGSM/issues/4309

**Comment by JackoPlane** [comment] 2023-10-27 20:42
Add `-logfile ${consolelog}` to your start parameters

**Comment by dgibbs64** [comment] 2024-06-13 13:29
-logfile ${gamelog} is the current default. I will close this issue as logs are working as intended by the game server and/or mod

**Closed by dgibbs64** 2024-06-13 13:29 UTC
Labels: type: bug, distro: Ubuntu, distro: Debian, distro: CentOS, game: Rust, command: install, command: start, command: console, distro: Rocky Linux
