### ISSUE TITLE
[ts3server] blacklisted from 4players.de add support for another mirror

### ISSUE THREAD

**Issue by darioriccioni** [GameServerManagers/LinuxGSM#1124] opened 2016-10-15 17:37 UTC
As a server admin my server is blacklisted from using 4netplayers. I would like to add support for other mirrors.

As the title says, I'm using the script to install a TeamSpeak server, but the script can't get the version from teamspeak.com and ends with an error, this one:
# Installing TeamSpeak 3 Server

```
fetching update_ts3.sh...OK
```

[ FAIL ] Update ts3-server: Checking for update: teamspeak.com: Not returning version info    fetching core_exit.sh...OK

and right after fetching core_exit.sh the script ends. Any way to solve this?

**Comment by cedarlug** [comment] 2016-10-15 17:44
Can you try issuing:
```
./ts3server uf
```
and trying the update again?

**Comment by UltimateByte** [comment] 2016-10-15 18:18
Can't reproduce. Bet on outdated functions.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by darioriccioni** [comment] 2016-10-16 05:22
Tried doing

./ts3server uf

and then retry installing the server and got the same error

[ FAIL ] Update ts3-server: Checking for update: teamspeak.com: Not returning version

Tried even deleting everything and redoing it from zero, without any result.

This is the result of ./ts3server postdetails: http://hastebin.com/sovejukaye

This is the content of the only log file I can find:

Oct 16 00:05:17 ts3-server: INSTALL: INFO: Logs installed
Oct 16 00:05:17 ts3-server: INSTALL: PASS: downloading check_deps.sh: OK
Oct 16 00:05:22 ts3-server: INSTALL: PASS: downloading install_server_files.sh: OK
Oct 16 00:05:23 ts3-server: INSTALL: PASS: downloading update_ts3.sh: OK
Oct 16 00:06:33 ts3-server: ERROR: core_getopt.sh exiting with code: 2
Oct 16 00:06:45 ts3-server: PASS: downloading command_postdetails.sh: OK
Oct 16 00:06:45 ts3-server: postdetails: PASS: downloading command_details.sh: OK
Oct 16 00:06:46 ts3-server: CHECK: PASS: downloading check_system_dir.sh: OK
Oct 16 00:06:46 ts3-server: postdetails: PASS: downloading info_config.sh: OK
Oct 16 00:06:46 ts3-server: postdetails: PASS: downloading info_parms.sh: OK
Oct 16 00:06:48 ts3-server: postdetails: PASS: command_postdetails.sh exiting with code: 0
Oct 16 02:15:10 ts3-server: UPDATE: FATAL: Failure! Checking for update: teamspeak.com: Not returning version info
Oct 16 02:15:10 ts3-server: UPDATE: FATAL: update_ts3.sh exiting with code: 1
Oct 16 07:15:27 ts3-server: postdetails: PASS: command_postdetails.sh exiting with code: 0

The machine is a Scaleway.com VPS with 2 x86 cores, 2GB RAM and 50GB SSD. On this same machine I successfully installed a Rust test server (running smoothly even if 4GB RAM are reccomended for this kind of server) using your scripts.

**Comment by UltimateByte** [comment] 2016-10-16 08:17
Server IP:    :9987
Config file:        /home/ts3server/serverfiles/ts3-server.ini (FILE MISSING)

I suppose you have an outdated ts3server script since i successfully installed ts3 yesterday with the new one.

**Comment by darioriccioni** [comment] 2016-10-16 10:37
https://gameservermanagers.com/lgsm/ts3server/

**Comment by UltimateByte** [comment] 2016-10-16 10:48
Right before it got updated probably. Get it again, main script changed installation config a bit, for the best.

**Comment by darioriccioni** [comment] 2016-10-16 11:16
Downloaded again and even tried to get it from github here

https://github.com/GameServerManagers/LinuxGSM/raw/master/TeamSpeak3/ts3server

without any success, keeps getting stuck after fetching update_ts3.sh for a long time and then the error.

**Comment by cedarlug** [comment] 2016-10-16 11:45
Any chance you could manually edit the file lgsm/functions/update_ts3.sh?

First, can you report if the following 3 lines appear on line 106-107, or 111-112 (see below for a command to run for checking this)?

```
110        # Tidy up
111        rm -f "${lgsmdir}/tmp/.ts3_version_numbers_unsorted.tmp"
112        rm -f "${lgsmdir}/tmp/.ts3_version_numbers_sorted.tmp"
```
Either way - could you comment out these lines or simply remove them?

Then run the update again.  Afterward, post these two files to pastebin.  They can be found in 
`~ts3server/serverfiles/lgsm/tmp/.ts3_version_numbers_unsorted.tmp` and `~ts3server/serverfiles/lgsm/tmp/.ts3_version_numbers_sorted.tmp`

To recap:

- Could you please identify(*) if those two lines are on lines 106-107 or on lines 111-112?
- Could you please remove these lines or comment them out of the file?
- Could you please rerun the update command afterward?
- Could you please post the two files in question, found in ~ts3server/serverfiles/lgsm/tmp

(*) One way to determine this is to check whether you see these two lines on 105-106 with: 
```
lgsm@delli7:/tmp$ awk 'NR>=106&&NR<=107' lgsm/functions/update_ts3.sh 
        rm -f "${tmpdir}/.ts3_version_numbers_unsorted.tmp"
        rm -f "${tmpdir}/.ts3_version_numbers_sorted.tmp"
```
or on lines 111-112 with:
```
lgsm@delli7:~/LinuxGSM$ awk 'NR>=111&&NR<=112' lgsm/functions/update_ts3.sh 
        rm -f "${lgsmdir}/tmp/.ts3_version_numbers_unsorted.tmp"
        rm -f "${lgsmdir}/tmp/.ts3_version_numbers_sorted.tmp"
```

**Comment by darioriccioni** [comment] 2016-10-16 12:12
The 2 lines are on 106-107, commented them but can't find anywere those 2 temp files. Had a look at the running processes and it seems this is running when the script gets stuck, don't know if this could help:

wget http://dl.4players.de/ts/releases/?C=M;O=D -q -O -

**Comment by cedarlug** [comment] 2016-10-16 12:42
Okay - that helps.

Can you see if `find ~/serverfiles -name tmp -type d` returns anything?  If not, then we're closing in on your issue.

**Comment by darioriccioni** [comment] 2016-10-16 13:13
Tried to give that command but doesn't return anything... Anyway, to let you understand, the last post I sent was right after I relaunched again the script for a clean install and it's still running, still stuck at the same point. I'll try use that command again after I'll get the error and script ends to see if it returns anything, but this means I could have to wait hours...

**Comment by cedarlug** [comment] 2016-10-16 13:15
It should dump output into /tmp/postme.  Is there nothing there?

**Comment by cedarlug** [comment] 2016-10-16 13:18
If that command hangs, then something else is fishy.

Is it possible that you're blocking http connections? 
Does a simple ` wget http://yahoo.com -q -O -` also hang?

**Comment by darioriccioni** [comment] 2016-10-16 13:41
Nothing in /tmp/postme and the wget http://yahoo.com -q -O - doesn't hang

**Comment by cedarlug** [comment] 2016-10-16 14:15
So wget hangs to the 4players.de site, but not to others? How about curl:

```
curl -o /tmp/output "http://dl.4players.de/ts/releases/?C=M;O=D"
```

**Comment by UltimateByte** [comment] 2016-10-16 14:29
We've seen someone with its IP blocked from 4players once, might be it again. Well spotted @cedarlug

**Comment by cedarlug** [comment] 2016-10-16 14:32
Good old DDoS protection - Making life more secure for them by making it more difficult for the rest of us.

**Comment by UltimateByte** [comment] 2016-10-16 14:35
The only way to workaround this would be for us to mirror their server.
I could do it with some bash script, a subdomain virtualhosted, and a cronjob.

**Comment by darioriccioni** [comment] 2016-10-16 15:49
Yep we find what's the problem. Tried the command cedarlug told me to try and guess what? Stuck on 0%.

**Comment by UltimateByte** [comment] 2016-10-16 16:48
So @dgibbs64 @cedarlug @marvinl97 Should we mirror this server since many people seem to have trouble getting the files from it ?

**Comment by dgibbs64** [comment] 2016-10-16 16:51
Could do. I cannot see why not. Might be worth talking to the Teamspeak devs about it as well.

**Comment by UltimateByte** [comment] 2016-10-16 17:29
I can create a "misc" folder into lgsm, with the script we could use to deploy our mirrors.

**Comment by UltimateByte** [comment] 2016-10-17 15:36
@darioriccioni What you can do however is manually install ts3 in serverfiles, then LGSM will handle server management, except auto update won't be possible, for now, until we're able to do something.

**Comment by darioriccioni** [comment] 2016-10-17 18:36
Since I saw on the Teamspeak website that they use gamed!de alongside 4Netplayers for providing their files, is there a way to modify the scripts and try to let them work with gamed!de also?

**Comment by UltimateByte** [comment] 2016-10-17 18:59
If i remember well, 4netplayers can't be used to get the latest version as easilly (or at all) as 4players.de.

**Comment by darioriccioni** [comment] 2016-10-17 19:02
Err... 4netplayers and 4players.de are the same thing... And from what I saw, on gamed!de they're up to date with the releases. Even found out that what http://dl.4players.de/ts/releases/ is for 4netplayers, http://teamspeak.gameserver.gamed.de/ts3/releases/ is for gamed!de so they should work the same way.

**Comment by UltimateByte** [comment] 2016-10-17 22:23
So if you want this to work instantly, download it from client side, and upload the extracted zip to /home/ts3server/serverfiles
Then LGSM will handle it.
Otherwise, i'll mirror the thing,when i got time because it'll require a script to keep it updated, and so that we can have several mirrors.

**Comment by UltimateByte** [comment] 2016-11-07 18:54
So if you got an URL for ts3 (@Titou74 ), other than 4players.de, you can edit : 
update_ts3.sh

Use this file instead
http://hastebin.com/efajukeceq.bash

If you're editing by hand, note that i also removed fn_update_ts3_currentbuild from the bottom of the file.
Untested, but should work fine.
Of course you cannot update your installation this way, except maybe changing the URL and clearing old files in lgsm/tmp and running the installer again. Some data may be lost during such a process, so i cannot advise for it.

**Comment by lu4ki** [comment] 2017-01-10 19:35
Fixed update ts3.sh. He now works correctly with teamspeak.gameserver.gamed.de:
https://hastebin.com/tibegexiju.bash

**Comment by UltimateByte** [comment] 2017-01-11 01:22
Thanks @lu4ki 
Maybe we could try pinging servers before starting DL, then, ping the mirror you provided, and add a few messages to inform the user.

**Comment by dgibbs64** [comment] 2019-03-25 21:03
this mirror is no longer used so the issue should be resolved

**Closed by dgibbs64** 2019-03-25 21:03 UTC
Labels: type: bug, outcome: issue resolved, game: Teamspeak 3, engine: null
