### ISSUE TITLE
Insurgency Sandstorm

### ISSUE THREAD

**Issue by 0xlord** [GameServerManagers/LinuxGSM#2070] opened 2018-11-08 20:53 UTC
**What game server Would you like adding?**
Insurgency Sandstorm which dedicated server files got released today!

**Can you link to any tutorials or guides?**
https://docs.google.com/document/d/1GDLg5p9jjeIya7EgBk0ibzDtDlyQ-U_jpspOzby-JmM/edit

**Is the server on Steam?**
AppID: 581330

**Is the server supported on Linux?**
Yes, natively through SteamCMD

**Comment by Outpox** [comment] 2018-11-09 17:22
I already opened an issue #2004 in september :P

**Comment by dgibbs64** [comment] 2018-11-09 17:31
Thanks for the update. This will be planed for the next release.

**Comment by dgibbs64** [comment] 2018-11-14 16:07
duplicate of #2004 2004

**Closed by dgibbs64** 2018-11-14 16:07 UTC
Labels: triage
