### ISSUE TITLE
7dtd server crashes after starting

### ISSUE THREAD

**Issue by dementedusa** [GameServerManagers/LinuxGSM#1139] opened 2016-10-20 00:03 UTC
I have had many succesful server with lgsm including a sdtd server.   we had to wipe our server and start from scratch and our sdtd server is just not working.  I have check the forums and googled the problem but have not come up with an answer.  the latest log   http://pastebin.com/ZCtnrd83   and the hastebin
http://pastebin.com/dHKWzata     I have two kf server running right now and flawlessly.  I just dont know what to do

**Comment by UltimateByte** [comment] 2016-10-20 02:12
Hey there,

Congrats for providing some proper outputs though, it's too rare for not being mentioned.
This seems pretty similar to this: https://github.com/GameServerManagers/LinuxGSM/issues/1103
I closed the issue since no feedback and no useful info was provided.

I've been able to reproduce the issue upon a fresh install, which should not happen.
Even a debug start won't do anything.

I checked all ports to see if some were used, and 26901 is actually used by an srcds_linux i have.
```
root@game:/home/ultimatebyte/sdtd# netstat -atunp | grep 26901
udp        0      0 164.132.201.49:26901    0.0.0.0:*                           20510/srcds_linux
```
So i tried using a different port... No luck. Found out 26900 to 26911 are all used. So trying again with 26912... Still no luck.

So, with different start parameters, finally some server initialization
```
[  OK  ] Debug sdtd-server: Starting debug
Set current directory to /home/ultimatebyte/sdtd/serverfiles
Found path: /home/ultimatebyte/sdtd/serverfiles/7DaysToDieServer.x86
Mono path[0] = '/home/ultimatebyte/sdtd/serverfiles/7DaysToDieServer_Data/Managed'
Mono path[1] = '/home/ultimatebyte/sdtd/serverfiles/7DaysToDieServer_Data/Mono'
Mono config path = '/home/ultimatebyte/sdtd/serverfiles/7DaysToDieServer_Data/Mono/etc'
```
But then it shuts down.

Tried with default config (just changing port), same issue. Tried minimalist start parameters, same issue.

Don't have more clue, i think it's a game issue here.

**Comment by UltimateByte** [comment] 2016-10-20 02:23
Can you please report that Linux server is broken here, since you own the game ? http://steamcommunity.com/app/251570/discussions/1/
And link them to this github issue so that maybe we got a chance to talk to the devs.

**Comment by dementedusa** [comment] 2016-10-21 01:07
posted

**Comment by UltimateByte** [comment] 2016-10-23 11:54
Link ?

**Comment by killerty69** [comment] 2016-11-01 23:02
I already fixed this issue, you can close it on here.

**Comment by UltimateByte** [comment] 2016-11-02 00:43
@killerty69 Really ? I didn't see the commit. Any link to the fix ?

**Closed** 2016-11-09 17:21 UTC
Labels: type: bug, game: 7 Days to Die, engine: unity3d

**Comment by UltimateByte** [comment] 2016-11-09 18:17
Wait, is it fixed or not ?

**Comment by dementedusa** [comment] 2016-11-09 18:21
yes it is fixed.  tried again and it worked flawlessley

**Comment by UltimateByte** [comment] 2016-11-09 18:29
Thanks for feedback.
