### ISSUE TITLE
Ark-Server stop, stop Arma3 Server too

### ISSUE THREAD

**Issue by Tealk** [GameServerManagers/LinuxGSM#1379] opened 2017-03-22 10:42 UTC
Hi,

if i stop my Ark-Server the Ark script stops the Arma3 Server too, but the Arma3 script doesn't stop the Ark Server.
Ark and Arma are both in the same folder and use both the same user
```
steam/_ark
     /_arma3
```

Postdetails:
Arma3: https://hastebin.com/ebavinapes
Ark: https://hastebin.com/iqogayejik

Arma3 console log:
```
5:59:55 "TERRITORY SYSTEM: _realLoopTime was 10.0156"
^C-tark-server 6:00:05 EPE manager release (94|417|0)
 6:00:05 Number of joints in scene after release: 14
```

Debian GNU/Linux 8.7 (jessie) (3.16.0-4-amd64)

Intel Xeon E5-1650V2; 64 GB DDR3 ECC reg.;

**Comment by UltimateByte** [comment] 2017-03-22 11:33
Hi,
`postdetails` output for each server is required if you want us to understand and reproduce the issue.
As per: https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Comment by Tealk144** [comment] 2017-03-22 11:47
Have update my first post, but why is there my admin password in cleartext in the postdetails?
https://hastebin.com/ebavinapes

`Admin  d4sbraucht3hkein3r  // Password to become server admin. When you're in Arma MP and connected to the server type '#login xyz'`

**Comment by UltimateByte** [comment] 2017-03-22 11:51
Sorry about that.
@cedarlug ?

**Comment by UltimateByte** [comment] 2017-03-22 12:00
Issue is probably here
https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/command_stop.sh#L265-L288

Awaiting for a fix, you can make separate users for these servers as advised https://github.com/GameServerManagers/LinuxGSM/wiki/Multiple-Servers

**Comment by UltimateByte** [comment] 2017-03-22 12:04
Could also be due to Arma3 using 27015 port, but seems unlikely.
With both servers started, can you please try this and provide the result ?

````bash
echo "$(netstat -nap 2>/dev/null | grep ^udp[[:space:]] |\
				grep :27015[[:space:]] | rev | awk '{print $1}' |\
				rev | cut -d\/ -f1)"
````

**Comment by Tealk144** [comment] 2017-03-22 12:09
echo "$(netstat -nap 2>/dev/null | grep ^udp[[:space:]] | grep :27015[[:space:]] | rev | awk '{print $1}' | rev | cut -d\/ -f1)"
15094

**Comment by Tealk144** [comment] 2017-03-22 14:27
@UltimateByte 
Have checked it again the server dosnt user the same port or something, only the same user^^
But the Ark server dosn't shut down clearly, it wait some time and then the script kill the server.

**Comment by Tealk144** [comment] 2017-03-24 10:43
have now make separate users for these servers but i still get this message:

[ .... ] Stopping ark-server: /home/ark/lgsm/functions/command_stop.sh: line 275: [: missing `]'
[  OK  ] Stopping ark-server:

**Comment by Tealk144** [comment] 2017-03-24 10:45
Have make separate users for these servers now.

**Comment by UltimateByte** [comment] 2017-03-24 12:42
Allright, I'll keep this opened for record when somebody (maybe me) works on diagnosing and solving this issue.
Thanks for your report.

**Comment by Tealk144** [comment] 2017-03-24 12:43
If you need help i can set up test servers :)

**Comment by UltimateByte** [comment] 2017-03-24 12:46
Thanks, but we're gonna be OK ! We all have our own servers, and @cedarlug provides a work machine for dev already ! No need for a specific install to test this, I'm pretty sure we're gonna be able to reproduce the issue thanks to the info you provided :)

**Comment by cedarlug** [comment] 2017-03-26 01:50
Looking into this further I have some answers and some questions.

First - the answer of your Admin line above -- The term "Password" in your comment on that line is being matched in `lgsm/functions/info_config.sh` when `command_details.sh` is parsing the config to dump the output to `command_postdetails.sh`.  I suspect that if you remove the comment, this line wont' appear in the output.

The other issue (the main issue) is still elusive. 

Can you copy-and-paste the screen output from `./arkserver stop` when it's killing arma3server?
```bash
script debug.dump
touch .dev-debug
./arkserver stop
exit
curl --upload-file debug.dump https://transfer.sh/debug.dump
rm debug.dump || /bin/true
```
and post the link.

**Comment by vadrozh** [comment] 2018-03-16 09:18
It's old topic but i have the same issue. I have the same csgoservers running under one user, and then you stop the first server, it stops the second server.

**Comment by Evolanca** [comment] 2018-04-12 08:41
Hello :) 

I also have the same issue. I try to make a Ark Cluster setup but its way more difficult than i thought ^^ Here what i tried: 

1. One installation with multiple servers. 
-- = Not possible if u wanna have different GameUserSettings or Mods.

2. Multiple installations with different Users.
-- = Doesnt work bcause Ark Clusterfiles are createt with the forced permissions u=rw,g=,o=  o. 077. So the other user can´t access the clusterfile even when i try to force other permissions via etc/.profile or in the specific user via ./profile or .bashrc. Nothing happens it is still 077. I also tried with running a cron to overwrite the permissions every minute that group can access and every user is in the same group but u still i have fail windows where u can lose the charakter or the upload. 

3. Multiple installations with one User
-- = Cluster works fine but now i have the problem that i only have one tmux session and when i shutdown the first server i started the rest got killed aswell. Seems that all instances are docked to the one session and when i kill the mainsession what is shown up in the tmux it will kill the rest aswell. When i shutdown all the servers except the first and the first at last it works fine. The problem is when this first server has issues it will inflict all the other ones and i have to shut down the whole cluster instead just starting that one server new. 

== One User with multiple instances is the best way but than i need for each server a own session to make it rly stand alone. 

Would be greate if someone has some ideas or maybe already a solution :)

**Comment by UltimateByte** [comment] 2018-04-16 21:37
@Evolanca This is going to be fixed soon. :) 
https://github.com/GameServerManagers/LinuxGSM/pull/1882

**Comment by UltimateByte** [comment] 2018-05-10 11:25
This should be fixed now ;)

**Closed by UltimateByte** 2018-05-10 11:25 UTC
Labels: Outcome: issue resolved, Type: bug
