### ISSUE TITLE
 jq: error (at <stdin>:0): Cannot iterate over null (null)

### ISSUE THREAD

**Issue by JasonPosterUpd** [GameServerManagers/LinuxGSM#2599] opened 2019-11-19 13:16 UTC
## Basic info

* Distro: Ubuntu 16.04
* Game: CS:GO
* Command: start

## Further Information

I have updated both lgsm and cs:go today and now I can't start server.
Every time I get this "server@vds111:~$ ./csgoserver start[ .... ] 
Starting csgoserver: jq: error (at <stdin>:0): Cannot iterate over null (null)"

**Comment by dgibbs64** [comment] 2019-11-20 18:25
This issue will be resolved in the next release

**Comment by mgjuhler** [comment] 2020-02-26 11:50
Have this bug been fixed?

Distro: Ubuntu 18.04.4 LTS
Game: csgo
LinuxGSM version: v19.12.5

```
lanu@csgo:~$ ./csgo27010 start
jq: error (at <stdin>:0): Cannot iterate over null (null)
jq: error (at <stdin>:0): Cannot iterate over null (null)
[ INFO ] Starting csgo27010: Check IP: 10.50.0.10
jq: error (at <stdin>:0): Cannot iterate over null (null)
[  OK  ] Starting csgo27010: Server 1
```

**Comment by Tobstr02** [comment] 2020-02-26 17:52
I also got the problem today with Ubuntu 18.04.4 LTS
Game: ark
LinuxGSM version: v19.12.5

**Comment by Ludestru** [comment] 2020-02-26 18:05
> I also got the problem today with Ubuntu 18.04.4 LTS
> Game: ark
> LinuxGSM version: v19.12.5

Did you check the permissions of the Engine/Binaries/Linux?

Try `sudo chown -R ~/serverfiles` and `chmod 775  -R  ~/serverfiles/Engine/Binaries/Linux/`.

For me it fixed the error.

**Comment by calvinsands** [comment] 2020-02-26 19:33
> > I also got the problem today with Ubuntu 18.04.4 LTS
> > Game: ark
> > LinuxGSM version: v19.12.5
> 
> Did you check the permissions of the Engine/Binaries/Linux?
> 
> Try `sudo chown -R arkserver:arkserver /home/arkserver/serverfiles` and `chmod 775 -R /home/arkserver/serverfiles/Engine/Binaries/Linux/`.
> 
> For me it fixed the error.

This helped me to discover that I'm actually missing /home/arkserver/serverfiles/Engine/Binaries/Linux/. This problem appeared immediately after I performed an automated force-update this morning at 10am EST. Curious to know if this is actually an ARK problem, not LGSM's.

**Comment by cyberlimbo** [comment] 2020-02-27 01:32
Debian 10.3 x64
Latest LinuxGSM

same happening with me..
"Try sudo chown -R arkserver:arkserver /home/arkserver/serverfiles and chmod 775 -R /home/arkserver/serverfiles/Engine/Binaries/Linux/"
Didnt fixed my problem.

**Comment by Tobstr02** [comment] 2020-02-27 07:19
I also got this problem.
@calvinsands Just go on https://survivetheark.com/index.php?/forums/topic/507564-genesis-dedicated-server-error/

Just download the file(from Google Drive from sirvulcan) and load it in the right directory.
It is missing since the last patch.

**Comment by dgibbs64** [comment] 2020-07-13 14:27
I believe this is now resolved. Please re-open if the issues returns

**Comment by UltimateByte** [comment] 2020-09-01 18:13
Same on 7Days to die. I believe it comes from the gathering of the config file.

**Comment by Robomikel** [comment] 2020-09-06 02:30
I am getting the same thing when running the details command. 

`sdtdserver@sdtdserver:~$ ./sdtdserver details  `
`[ INFO ] Viewing details sdtdserver: Check IP: 172.30.250.15  `
`jq: error (at <stdin>:0): Cannot iterate over null (null)  `
`jq: error (at <stdin>:0): Cannot iterate over null (null)  
`
I also noticed the port in the details is not accurate. I tried changing the port number from default in the server /home/sdtdserver/serverfiles/sdtdserver.xml and has no effect. still shows 

`Server IP:        172.30.250.15:2690026900269052701527020 `  
`Internet IP:      96.78.12.26:2690026900269052701527020`   
`DESCRIPTION  DIRECTION  PORT                       PROTOCOL`    
`> Game/RCON  INBOUND    2690026900269052701527020  udp `  
`> Query      INBOUND    2690026900269052701527020  udp`  


`Distro Details`
`=================================`
`Distro:    Ubuntu 18.04.5 LTS`
`Arch:      x86_64`
`Kernel:    4.15.0-115-generic`
`Hostname:  sdtdserver`
`Uptime:    0d, 0h, 17m`
`tmux:      tmux 2.6`
`glibc:     2.27`

**Comment by Tiscan** [comment] 2020-09-06 12:42
Hey, this has been discussed and fixed [here](https://github.com/GameServerManagers/LinuxGSM/issues/3006).

**Comment by Robomikel** [comment] 2020-09-06 13:43
> Hey, this has been discussed and fixed [here](https://github.com/GameServerManagers/LinuxGSM/issues/3006).

Nice, thanks. that worked. I thought a fix was pushed already.

 If you are reading this -
Edit: /home/sdtdserver/serverfiles/sdtdserver.xml 
line 13 - 
Delete: " Keep it in the ranges 26900 to 26905 or 27015 to 27020 if you want PCs on the same LAN to find it as a LAN server. "
Save.
Then run the details command again.

**Comment by h3o66** [comment] 2020-09-13 20:36
Closing as this is a differnt issue and the issue is discussed here: #3006

**Closed by h3o66** 2020-09-13 20:36 UTC
Labels: type: bug
