### ISSUE TITLE
Necesse Dedicated Server [Server Request]

### ISSUE THREAD

**Issue by eris667** [GameServerManagers/LinuxGSM#3974] opened 2022-09-03 16:10 UTC
## What game server would you like to add?
Necesse Dedicated Server

[game server]
https://steamdb.info/app/1169370/

## Can you link to any tutorials or guides?
https://steamdb.info/app/1169040/

Provide any useful documentation or resources that might help.
https://necessewiki.com/Multiplayer
https://necessewiki.com/Multiplayer-Linux

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[appid]
1169370
## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by Claiyc** [comment] 2022-09-03 16:13
Can be considered.
https://necessewiki.com/Multiplayer-Linux

**Comment by eris667** [comment] 2022-09-04 15:07
Found a duplicate of my request - I apologize
https://github.com/GameServerManagers/LinuxGSM/issues/3852

**Comment by Claiyc** [comment] 2022-09-04 15:16
Duplicate of #3852

**Closed by Claiyc** 2022-09-04 15:16 UTC
Labels: info: docs, potential-duplicate
