### ISSUE TITLE
Heavy /var/mail/csgoserver || warning: command substitution: ignored null byte in input

### ISSUE THREAD

**Issue by thclaude** [GameServerManagers/LinuxGSM#1199] opened 2016-11-23 01:28 UTC
Hi,

First of all, thanks for this amazing manager !

But I have one problem. The file 'csgoserver' in /var/mail is too heavy !!

When I take a look at this file, I can see manyyyy lines like this 

`/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input
/home/csgoserver/csgo5/lgsm/functions/monitor_gsquery.sh: line 53: warning: command substitution: ignored null byte in input`

It's the same for /home/csgoserver/csgo4/ ; /home/csgoserver/csgo3/ etc etc..

And when i take a look at line 53 in monitor_gsquery.sh i found this : 
`gsquerycmd=$("${functionsdir}"/gsquery.py -a "${ip}" -p "${port}" -e "${engine}" 2>&1)`

So there is any problem with this line ? And how can I fix that please ?

Thanks in advance !!

**Comment by Dessa** [comment] 2016-11-25 21:46
thats bash 4.4.
im not exactly sure what triggers that exactly now.

**Comment by UltimateByte** [comment] 2016-11-26 02:31
Things written to /var/mail/username are issues occuring for a given user. Here it seems like your system fails to set the variable properly for some reason.
I don't see any server info... Not even the distro version. How are we supposed to guess what the issue is ?
So if you wanna go further and hopefully get your issue solved, follow this "how to get help" guide https://github.com/GameServerManagers/LinuxGSM/wiki/Support
In addition, provide your bash version.

**Comment by tiibzbe** [comment] 2016-11-27 20:13
Hi, sorry for forgetting details. I'll try to be more precise : 

- All of my servers are running **CSGO**

- ./csgoserver postdetails : http://hastebin.com/orevelahis

- One exemple for the content of /var/mail/csgoserver : http://pastebin.com/7CD3mCZ7

-  **Distro :** Debian 7

- **lscpu** : http://pastebin.com/axMiMuT0

- **Bash Version** : GNU bash, version 4.4.5(1)-release (x86_64-pc-linux-gnu)

Hope this is precise.

**Comment by UltimateByte** [comment] 2016-11-28 01:25
Thanks for providing more info We can go further then.

My bash version on Debian 8.6 is `GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)`
Why would you have 4.4 ?
Oh... `Debian GNU/Linux unstable (sid)`
Well, i cannot recommend using unstable linux for production servers... As the name says, it's unstable and is probably the cause of the error that you see.
`Uptime:    4d, 1h, 32m` mh... not this, but still, 4d uptime is an advice for a user based issue.

After reviewing your log/mail example, my guess is that you're not redirecting output to `/dev/null 2>&1` in your cronjobs which causes mails to be sent locally.
If you're unsure what i'm talking about with /dev/null, see this: https://github.com/GameServerManagers/LinuxGSM/wiki/Cronjobs

PS: if you have a FQDN, then your hostname should be a subdomain of this FQDN, not ns386298, and this subdomain should point to your server IP. Just for a matter of a good practice.

**Comment by tiibzbe** [comment] 2016-11-30 15:17
I updated my distro and the problem is fixed now :)

Thanks for the answer !

**Closed** 2016-11-30 15:17 UTC
Labels: game: Counter-Strike: Global Offensive, engine: source
