### ISSUE TITLE
[Bug]: CentOS7 Core Keeper Server install/update Fail : Updating ckserver: No appmanifest_1963720.acf found

### ISSUE THREAD

**Issue by YukiNagado** [GameServerManagers/LinuxGSM#4277] opened 2023-07-28 16:20 UTC
### User story

Install ckserver with linuxGSM

### Game

Core Keeper

### Linux distro

RedHat 7, Other

### Command

command: update, command: install

### Further information

commend
./ckserver install
./ckserver update
show same error

### Relevant log output

```shell
[ ERROR ] Updating ckserver: No appmanifest_1963720.acf found
[ INFO ] Updating ckserver: Forcing update to correct issue
[ START ] Updating ckserver: SteamCMD
Redirecting stderr to '/home/ckserver/.local/share/Steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] Checking for available update...
KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]

../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
[----] !!! Fatal Error: Steamcmd needs to be online to update.   Please confirm your network connection and try again.
threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x56d27990/0x0xf7075b'
Complete! Updating ckserver: SteamCMD
[ FAIL ] Updating ckserver: Still no appmanifest_1963720.acf found
```

### Steps to reproduce

1. ./ckserver update
2. see error

**Comment by h3o66** [comment] 2023-07-28 17:29
look like a duplicate of #4276

**Comment by YukiNagado** [comment] 2023-07-29 16:15
> look like a duplicate of #4276

Yeah,
I think the same problem.

**Comment by kaonashi696** [comment] 2023-08-13 11:02
Any updates on this? I'm having the same issue installing sfserver

**Comment by dgibbs64** [comment] 2023-09-01 23:40
closes as duplicate

**Closed by dgibbs64** 2023-09-01 23:40 UTC
Labels: type: bug, info: steamcmd, distro: CentOS, command: install, command: update
