### ISSUE TITLE
[Server Request]

### ISSUE THREAD

**Issue by oyofeld** [GameServerManagers/LinuxGSM#3716] opened 2021-12-17 17:44 UTC
## What game server would you like to add?

The Isle Evrima Branch

## Can you link to any tutorials or guides?

Provide any useful documentation or resources that might help.

## Is the server on Steam?

* [x] Yes

If yes Use SteamDB to get the appid. (https://steamdb.info).

https://steamdb.info/app/412680/depots/?branch=evrima

## Is the server supported on Linux?

We only support Linux servers and do **not** support Wine.

'Yes' at time of writing current build is still waiting for linux release, but filling in this form anyway as advised by discord mod

**Comment by h3o66** [comment] 2021-12-17 17:48
Duplicate of #3715

**Closed by h3o66** 2021-12-17 17:48 UTC
Labels: info: docs, potential-duplicate
