### ISSUE TITLE
[Server Request] Citadel: Forged with Fire

### ISSUE THREAD

**Issue by cdokkum** [GameServerManagers/LinuxGSM#3520] opened 2021-07-25 15:09 UTC
## What game server would you like adding?

[Citadel: Forged with Fire]

## Can you link to any tutorials or guides?

https://steamcommunity.com/sharedfiles/filedetails/?id=1397348707

Provide any useful documentation or resources that might help.

https://steamcommunity.com/sharedfiles/filedetails/?id=1397348707

## Is the server on Steam?

* [x] Yes
* [ ] No

If yes Use SteamDB to get the appid. (https://steamdb.info).

[487120]

## Is the server supported on Linux?

* [x] Yes
* [ ] No

We only support Linux servers and do **not** support Wine.

* [x] Yes
* [ ] No

**Comment by gOOvER** [comment] 2021-07-25 15:20
Duplicate of #2220 & #1548

**Comment by Claiyc** [comment] 2022-03-24 08:11
Duplicate of #1548

**Closed by Claiyc** 2022-03-24 08:11 UTC
Labels: type: game server request
