### ISSUE TITLE
syntax error: operand expected (error token is "-")

### ISSUE THREAD

**Issue by Tealk144** [GameServerManagers/LinuxGSM#908] opened 2016-06-30 06:12 UTC
Hi, if i restart my Server i get this error:

```
[K[ .... ] Stopping ark-server: Arc
[K[ .... ] Stopping ark-server: Arc
[K[ .... ] Stopping ark-server: Process still bound. Awaiting graceful exit: 0
[K[ .... ] Stopping ark-server: Process still bound. Awaiting graceful exit: 1
[K[ .... ] Stopping ark-server: Process still bound. Awaiting graceful exit: 2/home/steam/lgsm/functions/command_stop.sh: line 183: let: -: syntax error: operand expected (error token is "-")
/home/steam/lgsm/functions/command_stop.sh: line 185: [[: -: syntax error: operand expected (error token is "-")


[K[[0;32m  OK  [0m] Stopping ark-server: Arc

[K[ .... ] Log Manager ark-server: Starting
[K[[0;32m  OK  [0m] Log Manager ark-server: Starting

[K[[0;36m INFO [0m] Log Manager ark-server: Removing logs older than 7 days

[K[[0;32m  OK  [0m] Log Manager ark-server: Removed 2 log files

[K[ .... ] Starting ark-server: Arc
[K[[0;32m  OK  [0m] Starting ark-server: Arc
```

**Comment by UltimateByte** [comment] 2016-06-30 09:27
@cedarlug ?
https://github.com/dgibbs64/linuxgsm/blob/master/lgsm/functions/command_stop.sh#L185

**Comment by cedarlug** [comment] 2016-06-30 14:44
Thanks for the head's up.   Checking.

**Comment by cedarlug** [comment] 2016-06-30 17:51
The good news is that the issue is benign.  The message does not effect the restart behavior.  

Pull request #909 will solve the issue and squash the error in the event the process id vanishes when queried (which is a GOOD thing).

**Comment by cedarlug** [comment] 2016-07-02 17:52
Closed with #909 integration.

**Comment by UltimateByte** [comment] 2016-07-03 00:39
run 
`./arkserver uf`
to get the update ;)

**Comment by Tealk144** [comment] 2016-07-03 07:37
@UltimateByte thanks, i have already added the updated part manually

**Comment by kbgvirus** [comment] 2016-08-12 06:54
Hi, Please note this issue is still happening as the command_stop.sh hasnt been updated with `pid=${pid//[!0-9]/}`

**Comment by UltimateByte** [comment] 2016-08-27 17:27
@kbgvirus 
What ?
Is this not enough ?
https://github.com/GameServerManagers/LinuxGSM/pull/909/files

`./arkserver uf` is required to get the update.

**Comment by kbgvirus** [comment] 2016-08-29 07:31
@UltimateByte i have added the line to the script and now getting another error, i will comment the error as i receive it.

**Comment by UltimateByte** [comment] 2016-08-29 09:15
Don't do that, run the update-functiions command as asked. Since it's another error, and this one is probably solved, i'm re-closing this.
I dont know if you're trolling or what, but this issue is solved.

**Comment by kbgvirus** [comment] 2016-08-29 09:17
@UltimateByte I am not trolling, if you read my first comment that new line had not been added to the stop script and therefore the error was still there

**Comment by UltimateByte** [comment] 2016-08-29 09:22
Well if you read the commit 909, you can see that the command has been added to command_stop.sh.
So that's why i don't get why you're still saying that.
Once again : https://github.com/GameServerManagers/LinuxGSM/pull/909/files

**Comment by kbgvirus** [comment] 2016-08-29 09:25
Thank you, there is no reason to troll a good cause

**Comment by UltimateByte** [comment] 2016-08-29 09:29
Sorry about my lack of trust, i don't know you & i assumed it had been merged to master directly. 
Well, let's put it to dev queue until merge.
And yeah, you can definitely add this manually until the merge then.

**Comment by kbgvirus** [comment] 2016-08-29 09:46
Thank You

**Comment by dgibbs64** [comment] 2016-09-01 19:03
@cedarlug I dont know why but im not sure this went in correctly. Please can you check the master repo and fix if missing. Thank you

**Comment by dgibbs64** [comment] 2016-09-01 20:31
@cedarlug https://github.com/GameServerManagers/LinuxGSM/commit/b8c82acbe8f2aa99cfd669b54d8c3ec274aedea3

**Comment by cedarlug** [comment] 2016-09-01 20:32
@kbgvirus - please update functions and verify that commit https://github.com/GameServerManagers/LinuxGSM/commit/b8c82acbe8f2aa99cfd669b54d8c3ec274aedea3 cleans up the issue.

**Closed by cedarlug** 2016-09-01 20:32 UTC
Labels: bug, under development
