### ISSUE TITLE
Stats not working on openvz vps

### ISSUE THREAD

**Issue by Frisasky** [GameServerManagers/LinuxGSM#2751] opened 2020-03-14 11:43 UTC
## User Story

It seems stats does not working on openvz vps, presumably due to limited kernel access of container
Testing on LXC would be welcomed

## Basic info

* **Distro:** [Ubuntu 16.04]
* **Game:** [Brainbread 2]
* **Command:** [Stats]
* **LinuxGSM version:** [v20.1.1]

## Further Information

uuid.txt not generated

## To Reproduce

Run any game server on openvz vps 

## Expected behaviour

File generated and server posted on usage page

**Comment by dgibbs64** [comment] 2020-03-15 16:28
I don't have an LXC environment. Id it something that could be set up in a Linode?

**Comment by Frisasky** [comment] 2020-03-15 16:36
yeah you can
if you want shortcut you could just buy an openvz/lxc vps, just costs few dollars per month

**Comment by Claiyc** [comment] 2022-03-23 22:11
Cannot reproduce on proxmox LXC (and should not be an issue). Closing this for now.

**Closed by Claiyc** 2022-03-23 22:11 UTC
Labels: type: bug, cannot reproduce, command: details
