### ISSUE TITLE
Updated LGSM. Now seeing "numfmt: invalid number: 'K'".

### ISSUE THREAD

**Issue by jrmain** [GameServerManagers/LinuxGSM#2005] opened 2018-09-09 12:35 UTC
**Describe the bug**
Since updating LGSM on September 8 (using update-lgsm), some LGSM commands are showing `numfmt: invalid number: 'K'`. Servers seem to be running fine otherwise. LGSM version shows as 170305. Tried installing UT99server from scratch and that's also showing the same error. Updated my other server (UT2K4) using update-lgsm and it's showing the same error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Update LGSM with update-lgsm.
2. Issue an LGSM command, such as DETAILS.
3. Examine the results.
4. See error: "numfmt: invalid number: 'K'" in the results.

**Expected behaviour**
No error messages.

** Minimum Information **
The game server I am running: UT99 (also UT2K4, also affected).
The link from `./gameserver postdetails` command: postdetails did not work. Manual attempt to use hastebin also failed. Server details pasted below (first is before LGSM updates, second is after clean re-install of LGSM and UT99 server).

**Additional context**
Excerpt of command output showing error in context:
```
ut99server@foghorn:~$ ./ut99server details
[ INFO ] Details ut99server: Check IP: 192.168.0.196
numfmt: invalid number: 'K'

Distro Details
==============================================================================================================================

Distro:    Ubuntu 14.04.5 LTS
```

Original server details (ANSI removed):
```
Distro Details
==============================================================================================================================
Distro:    Ubuntu 14.04.5 LTS
Arch:      x86_64
Kernel:    3.13.0-135-generic
Hostname:  foghorn
tmux:      tmux 2.0
GLIBC:     2.19

Performance
Uptime:    15d, 23h, 15m
Avg Load:  0.27, 0.46, 0.54

Mem:       total   used   free     cached
Physical:  7.5G    7.1G   430M     5.1G
Swap:      7.7G    836M   6.9G

Storage
==============================================================================================================================
Filesystem:      /dev/sda1
Total:           451G
Used:            106G
Available:       323G
LinuxGSM Total:  737M
Serverfiles:     613M

Unreal Tournament 99 Server Details
==============================================================================================================================
Server name:      JDRGaming UT99 Co-op
Server IP:        192.168.0.196:7777
Internet IP:      24.80.59.72:7777
Server password:  
Admin password:   redacted
Status:           ONLINE

ut99server Script Details
==============================================================================================================================
Service name:           ut99-server
ut99server version:     170305
User:                   ut99server
GLIBC required:         2.1
Discord alert:          on
Email alert:            on
Pushbullet alert:       off
IFTTT alert:            
Mailgun (email) alert:  
Pushover alert:         
Telegram alert:         
Location:               /home/ut99server
Config file:            /home/ut99server/serverfiles/System/ut99-server.ini

Backups
==============================================================================================================================
No Backups created

Command-line Parameters
==============================================================================================================================
./ucc-bin server AS-Hispeed.unr ini=/home/ut99server/serverfiles/System/ut99-server.ini

Ports
==============================================================================================================================
Change ports by editing the parameters in:
/home/ut99server/serverfiles/System/ut99-server.ini

Useful port diagnostic command:
netstat -atunp | grep ucc-bin

DESCRIPTION              DIRECTION  PORT         PROTOCOL  INI VARIABLE
> Game                   INBOUND    7777         udp       Port=7777
> Query                  INBOUND    7778         udp
< UdpLink Port (random)  OUTBOUND   +            udp
< Master server          OUTBOUND   28900/28902  tcp/udp
> WebAdmin               INBOUND    8076         tcp       ListenPort=8076

JDRGaming UT99 Co-op
 WebAdmin
==============================================================================================================================
WebAdmin enabled:   True
WebAdmin url:       http://192.168.0.196:8076
WebAdmin username:  redacted
WebAdmin password:  redacted

Status:	ONLINE


command_details.sh exiting with code: 0
```

After clean re-install:
```
[K[ .... ] Details ut99server: Check IP
[K[[36m INFO [0m] Details ut99server: Check IP: 192.168.0.196

[93mDistro Details[0m
==============================================================================================================================
[34mDistro:    [0mUbuntu 14.04.5 LTS
[34mArch:      [0mx86_64
[34mKernel:    [0m3.13.0-157-generic
[34mHostname:  [0mfoghorn
[34mtmux:      [0mtmux 2.0
[34mGLIBC:     [0m2.19

[93mPerformance[0m
[34mUptime:    [0m14d, 21h, 51m
[34mAvg Load:  [0m0.83, 0.77, 0.80

[34mMem:       [34mtotal  used   free      cached  available[0m
[34mPhysical:  [0m7.5GB   2.0GB  4.3GB     [0m
[34mSwap:      [0m7.7GB   420MB  7.3GB[0m

[93mStorage[0m
==============================================================================================================================
[34mFilesystem:      [0m/dev/sda1
[34mTotal:           [0m451G
[34mUsed:            [0m110G
[34mAvailable:       [0m319G
[34mLinuxGSM Total:  [0m1.6G
[34mServerfiles:     [0m287M

[92mUnreal Tournament 99 Server Details[0m
==============================================================================================================================
[34mServer name:      [0mLinuxGSM
[34mServer IP:        [0m192.168.0.196:7777
[34mServer password:  [0mNOT SET
[34mAdmin password:   [0mredacted
[34mDefault Map:      [0mDM-Deck16][
[34mStatus:           [31mOFFLINE[0m

[92mut99server Script Details[0m
==============================================================================================================================
[34mService name:           [0mut99server
[34mut99server version:     [0m180908
[34mUser:                   [0mut99server
[34mGLIBC required:         [32m2.1[0m
[34mDiscord alert:          [0moff
[34mEmail alert:            [0moff
[34mPushbullet alert:       [0moff
[34mIFTTT alert:            [0moff
[34mMailgun (email) alert:  [0moff
[34mPushover alert:         [0moff
[34mTelegram alert:         [0moff
[34mLocation:               [0m/home/ut99server
[34mConfig file:            [0m/home/ut99server/serverfiles/System/ut99server.ini

[92mBackups[0m
==============================================================================================================================
No Backups created

[92mCommand-line Parameters[0m
==============================================================================================================================
./ucc-bin server DM-Deck16][.unr ini=/home/ut99server/serverfiles/System/ut99server.ini

[92mPorts[0m
==============================================================================================================================
Change ports by editing the parameters in:
/home/ut99server/serverfiles/System/ut99server.ini

Useful port diagnostic command:
netstat -atunp | grep ucc-bin

DESCRIPTION              DIRECTION  PORT         PROTOCOL  INI VARIABLE
> Game                   INBOUND    7777         udp       Port=7777
> Query                  INBOUND    7778         udp
< UdpLink Port (random)  OUTBOUND   +            udp
< Master server          OUTBOUND   28900/28902  tcp/udp
> WebAdmin               INBOUND    8076         tcp       ListenPort=8076

[92mLinuxGSM WebAdmin[0m
==============================================================================================================================
[34mWebAdmin enabled:   [0mTrue
[34mWebAdmin url:       [0mhttp://192.168.0.196:8076
[34mWebAdmin username:  [0mredacted
[34mWebAdmin password:  [0mredacted

[34mStatus:	[31mOFFLINE[0m


command_details.sh exiting with code: 0
```

**Comment by jrmain** [comment] 2018-09-09 16:27
It's kind of a long shot, but I think the problem may be related to the new 'ansi' option. I've disabled ansi in my ut99 server config, and it had no effect: ANSI colours are still appearing everywhere. And some of the ANSI codes include 'K'.

**Comment by dgibbs64** [comment] 2018-09-09 20:18
I think I know where the issue is but I'm on my phone so can't bring it up currently

**Comment by jrmain** [comment] 2018-09-09 21:16
I just reinstalled my UT2004 server from scratch and it's doing the same thing.

**Comment by dgibbs64** [comment] 2018-09-10 11:48
I think its related to this https://github.com/GameServerManagers/LinuxGSM/pull/1971

**Comment by xxngle** [comment] 2018-09-19 12:53
Same for CS:GO server.

**Comment by Venopsis** [comment] 2018-09-30 16:03
Hi,
Having same issue since update LGSM for Project Zomboid Server to last version (180908).
![image](https://user-images.githubusercontent.com/949573/46259537-0e347180-c4db-11e8-8c5e-7cf753efedd3.png)

**Comment by Troopie** [comment] 2018-09-30 19:33
I have same issue at insurgency and KF2 server

**Comment by dgibbs64** [comment] 2018-09-30 19:56
I am aware of this issue. Should be fixed in next release. It doesnt break anything important :)

**Comment by dgibbs64** [comment] 2018-10-04 18:18
connects to #1971

**Comment by Venopsis** [comment] 2018-10-14 23:27
> I am not getting this issue. I think its related older distros like Ubuntu 14.04

Hello Daniel,

Here is the details of my server:
Distro:   CentOS Linux release 7.5.1804 (Core)
Arch:   x86_64
Kernel:   2.6.32-042stab120.18 (production) and 3.10.0-862.14.4.el7.x86_64 (testing server)

Let me know if you need more details to troubleshoot.

**Comment by dgibbs64** [comment] 2018-10-14 23:28
Odd I just tested the issue on CentOS 7 and the issue didnt occur

```
[root@li655-230 ~]# numfmt --to=iec --from=iec --suffix=B "$(grep ^MemTotal /proc/meminfo | awk '{print $2}')K"
3.8GB
[root@li6
```

**Comment by dgibbs64** [comment] 2018-10-14 23:30
Here are my details
```
=
Distro:    CentOS Linux 7 (Core)
Arch:      x86_64
Kernel:    3.10.0-862.11.6.el7.x86_64
Hostname:  li655-230.members.linode.com
tmux:      tmux 1.8
GLIBC:     2.17
```
Looks like you are only running kernel 2.6 which is really old

**Comment by Venopsis** [comment] 2018-10-14 23:33
If I try the same command than your previous message, I don't have error:
![image](https://user-images.githubusercontent.com/949573/46923596-0ff14f80-d01a-11e8-80ce-ea35c54fc786.png)

But when using start command, I got error:
![image](https://user-images.githubusercontent.com/949573/46923603-3616ef80-d01a-11e8-8c39-bd8a8d260a72.png)

Suppose not related but no more able to run my server on CentOS since last update as Glibcxx 3.4.21 not found. Post open on Official game forum to check as nothing fix this.

**Comment by Venopsis** [comment] 2018-10-14 23:36
> Here are my details
> 
> ```
> =
> Distro:    CentOS Linux 7 (Core)
> Arch:      x86_64
> Kernel:    3.10.0-862.11.6.el7.x86_64
> Hostname:  li655-230.members.linode.com
> tmux:      tmux 1.8
> GLIBC:     2.17
> ```
> Looks like you are only running kernel 2.6 which is really old

I have two server as mentionned (prod and testing). The testing one use recent Kernel (more recent than yours).

Just tried on testing and not having the issue at all.

Could be Kernel related? Not an expert.

**Comment by dgibbs64** [comment] 2018-10-14 23:40
Whats the kernel version of your testing server?

**Comment by dgibbs64** [comment] 2018-10-14 23:49
It is my guess that kernel 2.6 does not have numfmt or a very old version of it

**Comment by dgibbs64** [comment] 2018-10-14 23:55
what is the output of `numfmt --version` of the server that has the issue?

**Comment by jrmain** [comment] 2018-10-15 03:05
Not sure if you were asking me, but anyway: numfmt (GNU coreutils) 8.21.

**Comment by dgibbs64** [comment] 2018-10-15 19:33
@jrmain odd I can't replicate the issue myself. I am unsure of what is causing the issue but it seems limited to old distros

**Comment by jrmain** [comment] 2018-10-15 23:03
> 
> 
> @jrmain odd I can't replicate the issue myself. I am unsure of what is causing the issue but it seems limited to old distros

I can look at the code. Can you provide any hints as to what I'm looking for?

**Comment by dgibbs64** [comment] 2018-10-15 23:05
`info_distro.sh`

https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/info_distro.sh#L96

**Comment by jrmain** [comment] 2018-10-16 12:13
Looks like MemAvailable was added to the Linux kernel relatively recently, in 3.14. I'm running 3.13. 
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773

**Comment by W0lftastisch** [comment] 2018-10-20 05:12
Same here. 

My distro:
```
Distro:    Ubuntu 16.04.5 LTS
Arch:      x86_64
Kernel:    4.4.0-042stab133.2
tmux:      tmux 2.1
GLIBC:     2.23
```
If additional information is needed, let me know.

**Comment by marvinlehmann** [comment] 2018-10-22 19:08
Same with Debian on Windows (WSL):

Kernel: 4.4.0-17134-Microsoft
numfmt version: 8.26

**Comment by TuXEKRO** [comment] 2018-10-24 18:43
Same with:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by dgibbs64** [comment] 2018-10-24 20:15
I can't see a pattern to this issue currently

**Comment by jrmain** [comment] 2018-10-24 21:19
Maybe just stop using MemAvailable?

**Comment by dgibbs64** [comment] 2018-10-24 21:21
Yes that may be the only choice

**Comment by Bourne-ID** [comment] 2018-10-24 21:45
Could always do a check - if it exists then use it, otherwise we can estimate it. The full calculation is documented [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773) but do we need to be exact, or can we say 'if the linux kernel doesn't include MemoryAvailable then we estimate with the next best thing on the list?'

**Comment by Bourne-ID** [comment] 2018-10-24 21:54
To add, elastic does a check for MemAvailable - and if it exists uses it, otherwise calculates it from Free, Buffers and Cache ([link](https://github.com/elastic/gosigar/commit/33b3bbdc1464fb5c452434b755952ea54b1312ef#diff-85678a06a1a7795f712b7ee92c01b608R122))

**Comment by dgibbs64** [comment] 2018-10-27 21:49
https://github.com/GameServerManagers/LinuxGSM/pull/2058

**Closed by dgibbs64** 2018-10-27 21:49 UTC
Labels: Status: under development, Type: bug

**Comment by jrmain** [comment] 2018-10-28 15:31
Confirmed fixed with version 181027.
