### ISSUE TITLE
[ns2] Unable to load game_setup.xml on centos 7

### ISSUE THREAD

**Issue by rolandpoulter** [GameServerManagers/LinuxGSM#593] opened 2015-12-29 06:54 UTC
Not sure if this is the appropriate place for this. There is a thread on unknown worlds forum but it wasn't very helpful: http://forums.unknownworlds.com/discussion/136479/unable-to-load-game-setup-xml

I'm running this in a VM with CentOS 7 installed. Here is my console output:

```
GetInstanceCount currently unimplemented
[  0.000] Unbound/Unknown : Error: Invalid command line ()
[  0.006] Main : Filesystem initialized, cache enabled
Press Tab to open the console window
Press Ctrl-C to exit
Build 279
Linux
Server tickrate 30, client sendrate 20, bandwidth limit per player 51200
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 4920
Connected to Steam servers
Web server running at XXX.XXX.XXX.XXX:8080
[  1.662] Worker 00 : Error: Unable to open 'game_setup.xml' (usage 0x1)
[  1.662] Worker 00 : Error: Unable to load 'game_setup.xml'!
VAC Enabled
```

The web admin server responds with a page that says "Server loading..."
I can find the server in the games list, but it I can't fully join the server. It stays "Connecting..." for a while and eventually times out.

**Comment by UltimateByte** [comment] 2015-12-30 22:29
Hi there. I'm sorry for your issue. Seems like you're not the only one experiencing this, either windows and linux. I can guess that it's not a script issue and that you should try to address this to game devs.

**Comment by UltimateByte** [comment] 2015-12-30 22:33
Btw, "invalid command line" makes me think it could be a start option issue. Could you please copy your main script's parms="" line ?
Maybe they changed some start options. Do you have a changelog of their last update (or preferably their last server update).

**Comment by rolandpoulter** [comment] 2015-12-31 23:34
Here are the params, I'm not sure if the problem has to do with `config_path` or not.

```
./server_linux32 -name "NS2 Server" -port 27015 -webadmin -webdomain 104.167.104.110 -webuser admin -webpassword "admin" -webport 8080 -map ns2_summit -limit 18 -config_path "/home/ns2server/server1" -modstorage "/home/ns2server/server1/Workshop" -mods ""
```

Not sure where I can find a changelog, but I'll try to get one of the ns2 devs or someone with more experience running a ns2 server.

**Comment by UltimateByte** [comment] 2016-01-01 03:50
Maybe try with no parms and add them one by one to hopefully get one that's causing issues ?
Could possibly be a quote symbol issue as i got some.

**Comment by Turbine1991** [comment] 2016-01-06 04:35
Roland, I tried your runline exactly - substituting my IP address.

Having an empty mods field gave me "Error: Invalid command line ()" with other errors. Please remove it  for now and post your output. Mine started successfully without it.

```
./server_linux32 -name "NS2 Server" -port 27015 -webadmin -webdomain 104.167.104.110 -webuser admin -webpassword "admin" -webport 8080 -map ns2_summit -limit 18 -config_path "/home/ns2server/server1" -modstorage "/home/ns2server/server1/Workshop"
```

**Comment by jaredballou** [comment] 2016-01-06 05:02
Is this server available for free? I can try to reproduce it, I have CentOS 6 and 7 boxes here.

**Comment by Turbine1991** [comment] 2016-01-06 05:06
Hosting is free, the instructions are under the "Linux Setup" section of: http://wiki.unknownworlds.com/ns2/Dedicated_Server

**Comment by UltimateByte** [comment] 2016-01-06 14:24
Just tried installing, seems like you need a steam account owning this game to get it working.

**Comment by Turbine1991** [comment] 2016-01-07 00:27
Sorry, I'll clarify - any Steam account will work, it does not have to own the game for the dedicted server.

**Comment by UltimateByte** [comment] 2016-01-07 01:52
Thanks.

So i just tried under Debian 8.2 which is my server's distro, and got it working without an issue.

Here is my ns2server config : 

# Start Variables
defaultmap="ns2_summit"
port="27150"
maxplayers="24"
ip="37.187.152.67"
updateonstart="off"
servername="NS2 Server"
webadminuser="admin"
webadminpass="admin"
webadminport="8010"
configpath="server1"
modstorage="server1/Workshop"
mods=""
password=""
# Add the following line to the parms if you want a private server. Ensuring
# that the password variable above is not left empty.
# -password \"${password}\"

Do you have anything significatively different compared to that ?
Maybe your port 8080 is already used ? That's why i changed mine, i thought it was already in use (but it's actually not).

**Comment by Turbine1991** [comment] 2016-01-07 01:58
The OP seemed to have trouble with CentOS. Debian and Ubuntu seem to work off the bat.

**Comment by UltimateByte** [comment] 2016-01-07 02:14
The OP isn't responding anymore btw ://
Seems like you found the solution : remove the empty -mods ""
Anything else to add @Turbine1991 ?

**Comment by Turbine1991** [comment] 2016-01-07 02:16
I'm satisfied. :)

**Comment by UltimateByte** [comment] 2016-01-07 02:17
Thanks for your help mate :)

**Comment by rolandpoulter** [comment] 2016-01-08 00:51
Sorry for the delayed response. I tried removing `mods` and it did not resolve the issue unfortunately. No need to re-open the bug. I'll try to find help from the ns2 community since this is not a problem with this project.

BTW, removing mods gave me the same output either way:

```
$ ./server_linux32 -name "NS2 Server" -port 27015 -webadmin -webdomain 104.167.104.110 -webuser admin -webpassword "admin" -webport 8080 -map ns2_summit -limit 18 -config_path "/home/ns2server/server1" -modstorage "/home/ns2server/server1/Workshop"
GetInstanceCount currently unimplemented
[  0.000] Main : Filesystem initialized, cache enabled
Press Tab to open the console window
Press Ctrl-C to exit
Build 279
Linux
Server tickrate 30, client sendrate 20, bandwidth limit per player 51200
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 4920
Connected to Steam servers
Web server running at 104.167.104.110:8080
[  1.819] Worker 00 : Error: Unable to open 'game_setup.xml' (usage 0x1)
[  1.819] Worker 00 : Error: Unable to load 'game_setup.xml'!
VAC Enabled
```

**Comment by UltimateByte** [comment] 2016-01-08 00:57
Thought you left forever :p 
I'm interested in finding a solution as it could affect all CentOS users.
We could include a fix for that if you can figure out what's causing that issue.
Please, keep us informed !

**Comment by jaredballou** [comment] 2016-01-13 06:06
Are you using selinux? Run the following command:
getenforce
Also, do
ls -lZ game_setup.xml
and that'll give us the SELinux context. And, you've got the files owned by the game server user, and permissions are OK? If you want to create an account for me on the box, I'd be glad to pop in and take a peek.

**Comment by UltimateByte** [comment] 2016-01-22 22:28
Closing for now, please keep us informed if anything relevant to fix.
Otherwise, i advise you to use the steam forum for general support : https://steamcommunity.com/groups/linuxgsm/discussions

**Closed by UltimateByte** 2016-01-22 22:28 UTC
Labels: distro: CentOS, game: Natural Selection 2, engine: spark

**Comment by JLATORRE89** [comment] 2017-05-08 23:14
I know this post was closed; but I am experiencing the same issue.
Picking up with the information that @jaredballou requested:
[ns2server@ns2 ns2]$ ls -lZ game_setup.xml
-rwxrwxr-x. ns2server ns2server unconfined_u:object_r:user_home_t:s0 game_setup.xml

Additional Information:
[ns2server@ns2 ns2]$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
Firewall dump:
[root@ns2 ~]# firewall-cmd --list-ports
27015/tcp 27015/udp 27016/udp 8080/tcp 8081/tcp 27016/tcp
[ns2server@ns2 ns2]$ sestatus
SELinux status:                 disabled

Running the command directly using:
./server_linux32 -name \" Awesome NS2 Server\" -port 27015 -webadmin -webdomain "192.168.1.26" -webuser ##admin## -webpassword ##password## -webport 8080 -map ns2_summit -limit 16

Documentation: https://wiki.unknownworlds.com/ns2/Dedicated_Server#CentOS

**Comment by Turbine1991** [comment] 2017-05-09 08:49
Does the server appear to connect to? It may not be an error, more a warning.

**Comment by JLATORRE89** [comment] 2017-05-10 15:43
@Turbine1991 negative, I cannot see the server in the game server listing.
The server status page still displays "Loading server..." after 10 minutes.
Did a complete reinstall of the OS and followed: https://gameservermanagers.com/lgsm/ns2server/
Same result.

**Comment by Turbine1991** [comment] 2017-05-10 16:05
What's your runline?

**Comment by JLATORRE89** [comment] 2017-05-11 00:27
@Turbine1991 by runline do you mean what command do I use to start the server?
After installing the script, I use the default command: ./ns2server start
executed from: /home/ns2server

**Comment by Turbine1991** [comment] 2017-05-11 04:10
@JLATORRE89 I forgot this is for a server manager. You should try set it up natively and run it, just to rule out whether it's a manager issue or a system issue.

Although I do run NS2 on Ubuntu. CentOS is too slow for game hosting imo, it's just too outdated (very stable) and not very optimised. Are you stuck to using this OS?

**Comment by JLATORRE89** [comment] 2017-05-11 22:40
@Turbine1991 I pretty much went with CentOS 7 because it is based on RHEL and is fairly stable.
I spun up another VM that is running Ubuntu 16, used the server manager; I can now see the dashboard as expected.

A key difference I noticed was fixes were not applied during the CentOS 7 install.
The manual install for CentOS 7 did not work either. I will make a note on the NS2 forum.

Ubuntu start:
[ WARN ] Starting ns2-server: Configuration file missing!
/home/ns2server/server1

Downloading Natural Selection 2 Config
=================================
default configs from https://github.com/GameServerManagers/Game-Server-Configs
    fetching check_ip.sh...OK
    fetching info_config.sh...OK
    fetching check_status.sh...OK
    fetching fix_steamcmd.sh...OK
[ .... ] Fix ns2-server: Applying steamclient.so general fix: Natural Selection [ INFO ] Fix ns2-server: Applying steamclient.so general fix: Natural Selection [  OK  ] Fix ns2-server: Applying steamclient.so general fix: Natural Selection 2
    fetching logs.sh...OK
[  OK  ] Starting ns2-server: Zuper Rookie Server


Thanks for all the help! =]

**Comment by Turbine1991** [comment] 2017-05-12 02:54
I wouldn't call small game servers mission critical, for NS2 I'd think performance is as important as stability. I've never had it crash/lock up on me since they fixed the crashes a long time ago.
