### ISSUE TITLE
Counter Strike is not installed

### ISSUE THREAD

**Issue by broonu** [GameServerManagers/LinuxGSM#1461] opened 2017-06-05 17:59 UTC
The install script runs without warnings, but game is not installed:

Installing:
=================================
    csserver@mediaserver:~$ ./csserver ai
    fetching core_dl.sh...OK
    fetching core_functions.sh...OK
    fetching core_trap.sh...OK
    fetching core_messages.sh...OK
    fetching core_getopt.sh...OK
    fetching command_install.sh...OK
    fetching check.sh...OK
    fetching check_root.sh...OK
    fetching check_tmuxception.sh...OK
    fetching check_permissions.sh...OK
    fetching check_glibc.sh...OK
    fetching info_glibc.sh...OK
    fetching info_distro.sh...OK
    fetching check_system_requirements.sh...OK
    fetching install_header.sh...OK
    =================================
    Counter-Strike 1.6
    Linux Game Server Manager
    by Daniel Gibbs
    Contributors: http://goo.gl/qLmitD
    https://gameservermanagers.com
    =================================
    fetching install_server_dir.sh...OK

    Server Directory
    =================================
    /home/csserver

    mkdir: created directory ‘/home/csserver/serverfiles’
        fetching install_logs.sh...OK

    Creating log directories
    =================================
    mkdir: created directory ‘/home/csserver/log’
    mkdir: created directory ‘/home/csserver/log/script’
    mkdir: created directory ‘/home/csserver/log/console’
    mkdir: created directory ‘/home/csserver/serverfiles/cstrike’
    mkdir: created directory ‘/home/csserver/serverfiles/cstrike/logs’
    ‘/home/csserver/log/server’ -> ‘/home/csserver/serverfiles/cstrike/logs’
        fetching check_deps.sh...OK

    Checking Dependencies
    =================================
    tmux
    wget
    ca-certificates
    file
    bsdmainutils
    util-linux
    python
    bzip2
    gzip
    unzip
    binutils
    lib32gcc1
    libstdc++6:i386
        fetching install_steamcmd.sh...OK

    Installing SteamCMD
    =================================
        fetching check_steamcmd.sh...OK
    mkdir: created directory ‘/home/csserver/steamcmd’
    ######################################################################## 100.0%
    downloading steamcmd_linux.tar.gz...OK
    extracting steamcmd_linux.tar.gz...OK
        fetching install_server_files.sh...OK

    Installing Counter-Strike 1.6 Server
    =================================
    Redirecting stderr to '/home/csserver/Steam/logs/stderr.txt'
    ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
    [  0%] Checking for available update...
    [  0%] Downloading update (0 of 18,553 KB)...
    [  0%] Downloading update (32 of 18,553 KB)...
    [  0%] Downloading update (268 of 18,553 KB)...
    [  1%] Downloading update (818 of 18,553 KB)...
    [  4%] Downloading update (1,566 of 18,553 KB)...
    [  8%] Downloading update (2,321 of 18,553 KB)...
    [ 12%] Downloading update (2,987 of 18,553 KB)...
    [ 16%] Downloading update (3,330 of 18,553 KB)...
    [ 17%] Downloading update (3,740 of 18,553 KB)...
    [ 20%] Downloading update (4,055 of 18,553 KB)...
    [ 21%] Downloading update (4,478 of 18,553 KB)...
    [ 24%] Downloading update (4,901 of 18,553 KB)...
    [ 26%] Downloading update (5,276 of 18,553 KB)...
    [ 28%] Downloading update (5,692 of 18,553 KB)...
    [ 30%] Downloading update (6,063 of 18,553 KB)...
    [ 32%] Downloading update (6,276 of 18,553 KB)...
    [ 33%] Downloading update (6,557 of 18,553 KB)...
    [ 35%] Downloading update (6,942 of 18,553 KB)...
    [ 37%] Downloading update (7,365 of 18,553 KB)...
    [ 39%] Downloading update (7,775 of 18,553 KB)...
    [ 41%] Downloading update (8,104 of 18,553 KB)...
    [ 43%] Downloading update (8,526 of 18,553 KB)...
    [ 45%] Downloading update (8,941 of 18,553 KB)...
    [ 48%] Downloading update (9,378 of 18,553 KB)...
    [ 50%] Downloading update (9,747 of 18,553 KB)...
    [ 52%] Downloading update (10,117 of 18,553 KB)...
    [ 54%] Downloading update (10,561 of 18,553 KB)...
    [ 56%] Downloading update (10,962 of 18,553 KB)...
    [ 59%] Downloading update (11,340 of 18,553 KB)...
    [ 61%] Downloading update (11,733 of 18,553 KB)...
    [ 63%] Downloading update (12,155 of 18,553 KB)...
    [ 65%] Downloading update (12,578 of 18,553 KB)...
    [ 67%] Downloading update (12,956 of 18,553 KB)...
    [ 69%] Downloading update (13,375 of 18,553 KB)...
    [ 72%] Downloading update (13,783 of 18,553 KB)...
    [ 74%] Downloading update (14,170 of 18,553 KB)...
    [ 76%] Downloading update (14,593 of 18,553 KB)...
    [ 78%] Downloading update (14,979 of 18,553 KB)...
    [ 80%] Downloading update (15,397 of 18,553 KB)...
    [ 82%] Downloading update (15,790 of 18,553 KB)...
    [ 85%] Downloading update (16,242 of 18,553 KB)...
    [ 87%] Downloading update (16,642 of 18,553 KB)...
    [ 89%] Downloading update (17,022 of 18,553 KB)...
    [ 91%] Downloading update (17,415 of 18,553 KB)...
    [ 93%] Downloading update (17,737 of 18,553 KB)...
    [ 95%] Downloading update (18,185 of 18,553 KB)...
    [ 98%] Downloading update (18,553 of 18,553 KB)...
    [100%] Download Complete.
    [----] Applying update...
    [----] Extracting package...
    [----] Extracting package...
    [----] Extracting package...
    [----] Installing update...
    [----] Installing update...
    [----] Installing update...
    [----] Installing update...
    [----] Cleaning up...
    [----] Update complete, launching...
    Redirecting stderr to '/home/csserver/Steam/logs/stderr.txt'
    [  0%] Checking for available updates...
    [----] Downloading update (0 of 12,673 KB)...
    [  0%] Downloading update (22 of 12,673 KB)...
    [  0%] Downloading update (1,152 of 12,673 KB)...
    [  9%] Downloading update (2,063 of 12,673 KB)...
    [ 16%] Downloading update (3,066 of 12,673 KB)...
    [ 24%] Downloading update (4,398 of 12,673 KB)...
    [ 34%] Downloading update (4,910 of 12,673 KB)...
    [ 38%] Downloading update (5,739 of 12,673 KB)...
    [ 45%] Downloading update (6,445 of 12,673 KB)...
    [ 50%] Downloading update (7,102 of 12,673 KB)...
    [ 56%] Downloading update (7,951 of 12,673 KB)...
    [ 62%] Downloading update (8,493 of 12,673 KB)...
    [ 67%] Downloading update (9,304 of 12,673 KB)...
    [ 73%] Downloading update (10,029 of 12,673 KB)...
    [ 79%] Downloading update (10,541 of 12,673 KB)...
    [ 83%] Downloading update (11,035 of 12,673 KB)...
    [ 87%] Downloading update (11,677 of 12,673 KB)...
    [ 92%] Downloading update (12,571 of 12,673 KB)...
    [ 99%] Downloading update (12,673 of 12,673 KB)...
    [100%] Download complete.
    [----] Installing update...
    [----] Extracting package...
    [----] Extracting package...
    [----] Extracting package...
    [----] Installing update...
    [----] Installing update...
    [----] Installing update...
    [----] Installing update...
    [----] Cleaning up...
    [----] Update complete, launching Steamcmd...
    Redirecting stderr to '/home/csserver/Steam/logs/stderr.txt'
    [  0%] Checking for available updates...
    [----] Verifying installation...
    Steam Console Client (c) Valve Corporation
    -- type 'quit' to exit --
    Loading Steam API...OK.

    Connecting anonymously to Steam Public...Logged in OK
    Waiting for license info...OK
     Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
     Update state (0x61) downloading, progress: 2.19 (1455184 / 66393415)
    Success! App '90' fully installed.
    Information! Goldsource servers commonly fail to download all the server files required. Validating a few of times may reduce the chance of this issue.
    Redirecting stderr to '/home/csserver/Steam/logs/stderr.txt'
    [  0%] Checking for available updates...
    [----] Verifying installation...
    Steam Console Client (c) Valve Corporation
    -- type 'quit' to exit --
    Loading Steam API...OK.

    Connecting anonymously to Steam Public...Logged in OK
    Waiting for license info...OK
     Update state (0x5) validating, progress: 9.48 (6291456 / 66393415)
    Success! App '90' fully installed.
    Redirecting stderr to '/home/csserver/Steam/logs/stderr.txt'
    [  0%] Checking for available updates...
    [----] Verifying installation...
    Steam Console Client (c) Valve Corporation
    -- type 'quit' to exit --
    Loading Steam API...OK.

    Connecting anonymously to Steam Public...Logged in OK
    Waiting for license info...OK
     Update state (0x5) validating, progress: 9.48 (6291456 / 66393415)
    Success! App '90' fully installed.
    Redirecting stderr to '/home/csserver/Steam/logs/stderr.txt'
    [  0%] Checking for available updates...
    [----] Verifying installation...
    Steam Console Client (c) Valve Corporation
    -- type 'quit' to exit --
    Loading Steam API...OK.

    Connecting anonymously to Steam Public...Logged in OK
    Waiting for license info...OK
     Update state (0x5) validating, progress: 3.16 (2097152 / 66393415)
    Success! App '90' fully installed.
    Redirecting stderr to '/home/csserver/Steam/logs/stderr.txt'
    [  0%] Checking for available updates...
    [----] Verifying installation...
    Steam Console Client (c) Valve Corporation
    -- type 'quit' to exit --
    Loading Steam API...OK.

    Connecting anonymously to Steam Public...Logged in OK
    Waiting for license info...OK
     Update state (0x5) validating, progress: 0.00 (0 / 66393415)
     Update state (0x5) validating, progress: 83.95 (55738955 / 66393415)
    Success! App '90' fully installed.
    Redirecting stderr to '/home/csserver/Steam/logs/stderr.txt'
    [  0%] Checking for available updates...
    [----] Verifying installation...
    Steam Console Client (c) Valve Corporation
    -- type 'quit' to exit --
    Loading Steam API...OK.

    Connecting anonymously to Steam Public...Logged in OK
    Waiting for license info...OK
     Update state (0x5) validating, progress: 0.00 (0 / 66393415)
     Update state (0x5) validating, progress: 68.67 (45592313 / 66393415)
    Success! App '90' fully installed.
        fetching install_config.sh...OK

    Downloading Counter-Strike 1.6 Config
    =================================
    default configs from https://github.com/GameServerManagers/Game-Server-Configs
    mkdir: created directory ‘/home/csserver/lgsm/default-configs’
        fetching server.cfg...OK
    copying server.cfg config file.
    ‘/home/csserver/lgsm/default-configs/server.cfg’ -> ‘/home/csserver/serverfiles/cstrike/cs-server.cfg’
    changing hostname.
    changing rcon/admin password.
        fetching fix.sh...OK
        fetching install_complete.sh...OK
    =================================
    Install Complete!

    To start server type:
    ./csserver start

        fetching core_exit.sh...OK

Running:
=================================
    csserver@mediaserver:~$ ./csserver d
    fetching command_debug.sh...OK
    fetching check_system_dir.sh...OK
    fetching check_logs.sh...OK
    fetching check_config.sh...OK
    fetching check_ip.sh...OK
    fetching info_config.sh...OK
    fetching fix_steamcmd.sh...OK
    [  OK  ] Fix cs-server: Applying steamclient.so general fix: Counter-Strike 1.6

    Counter-Strike 1.6 Debug
    =================================

    Distro: Debian GNU/Linux 8 (jessie)
    Arch:   x86_64
    Kernel: 3.16.0-4-amd64
    Hostname:       mediaserver
    tmux:   tmux 1.9
    Avg Load:       0.15, 0.20, 0.18
    Free Memory:    4.6G
    Free Disk:      9.4G
    GLIBC required: 2.3.4
    Server IP:      AAA.BBB.CCC.DDD:27015
    Server password:        NOT SET

    Start parameters:
    ./hlds_run -game cstrike -strictportbind +ip AAA.BBB.CCC.DDD -port 27015 +clientport 27005 +map de_dust2 -maxplayers 16 -debug

    Use for identifying server issues only!
    Press CTRL+c to drop out of debug mode.
    Warning! If cs-server is already running it will be stopped.

    Continue? [Y/n] Y
    [ INFO ] Debug cs-server: Stopping any running servers
        fetching command_stop.sh...OK
    [ .... ] Stopping cs-server: LinuxGSM    fetching check_status.sh...OK
    [ INFO ] Stopping cs-server: LinuxGSM is already stopped
    [  OK  ] Debug cs-server: Starting debug
    Enabling debug mode
    Auto-restarting the server on crash

    Console initialized.
    Using breakpad crash handler
    Setting breakpad minidump AppID = 10
    Forcing breakpad minidump interfaces to load
    Looking up breakpad interfaces from steamclient
    Calling BreakpadMiniDumpSystemInit
    FATAL ERROR (shutting down): W_LoadWadFile: couldn't load gfx.wad
    email debug.log to linux@valvesoftware.com
    Mon Jun  5 14:40:55 BRT 2017: Server restart in 10 seconds

**Comment by MarkL4YG** [comment] 2017-06-05 18:27
Yet another duplicate of #1450

**Comment by broonu** [comment] 2017-06-05 18:41
Maybe, but that workaround didn't work for 1.6.

**Comment by Twonkk** [comment] 2017-06-05 21:18
Need to use steam account and steam cms to login and do download.... have tested this on 6 different installs

**Comment by UltimateByte** [comment] 2017-06-05 23:24
Yet another post not following rules.
https://github.com/GameServerManagers/LinuxGSM/wiki/Support

**Closed by UltimateByte** 2017-06-05 23:24 UTC
Labels: duplicate
