### ISSUE TITLE
Feature Add in command line of CS1.6/CZServer

### ISSUE THREAD

**Issue by SanjaySRocks** [GameServerManagers/LinuxGSM#2632] opened 2019-12-01 10:12 UTC
I want you to update command line of cs 1.6 and cz server and add new variable called

systickrate="1000"
pingboost="2"

+sys_ticrate ${systickrate}
-pingboost ${pingboost}

**Comment by Frisasky** [comment] 2019-12-02 08:06
1) i have no idea what "systickrate" does, cant find anything about this parameter on internet
2) pingboost usually either cause the server hanging or exceed cpu usage so generally its not a good idea to enable it, it may be helpful in the situation that high latency is caused by infrastructure (ie poor connection quality). but since absolute majority of lgsm user located in EU or NA it seldom to be problem

**Comment by SanjaySRocks** [comment] 2019-12-02 09:49
You can search sys_ticrate and it's used to increase server fps to 1000.

**Comment by dgibbs64** [comment] 2019-12-10 10:03
This type of customisation is down o the individual server admin to manage. Having LinuxGSM adjusting performance settings would set us down a rabbit hole, so is out of scope for the project

**Closed by dgibbs64** 2019-12-10 10:03 UTC
Labels: type: feature request
