### ISSUE TITLE
Project Zomboid don't use "server.ini" file on Debian Jessie

### ISSUE THREAD

**Issue by Audrik** [GameServerManagers/LinuxGSM#1190] opened 2016-11-18 08:24 UTC
Hello, I install the last script for Project Zomboid, but when I launch server it doesn't use the "server.ini" file and use one by default. I modify the .ini file I found in "/home/pzserver/Zomboid/Server/" but it doesn't use it at launch.

Please need help, because before it work perfectly with an old (around 3 month) script

**Comment by marvinl97** [comment] 2016-11-18 14:54
Thank you, I found the cause of the problem and fixed it. It was caused by wrong config names. The default is "servertest.ini" (not "server.ini") and "server.ini" (not "server.cfg") in the Game-Server-Configs repo. Furthermore config directories didn't get created because of a missing function call.

When the fix will be merged into the master branch, the config name will be the service name specified in the main script.

8f7f0495ce578780de9a52759b48f210314009f4

**Closed** 2016-11-18 16:19 UTC
Labels: bug, development queue
