### ISSUE TITLE
[BUG] mumble server cannot be installed

### ISSUE THREAD

**Issue by kdulep** [GameServerManagers/LinuxGSM#3799] opened 2022-02-22 18:49 UTC
## Basic info

* **Distro:** [Debian 11.2]
* **Game:** [Mumble]
* **Command:** [Install]
* **LinuxGSM version:** [v21.5.1]

## Further Information
Server install failed

## To Reproduce

Try to install Mumble server
[ FAIL ] Updating mumbleserver: Checking remote build:

## Expected behaviour
server installed

**Comment by Claiyc** [comment] 2022-02-23 07:17
Duplicate of #3777

**Closed by Claiyc** 2022-02-23 07:17 UTC
Labels: outcome: duplicate, distro: Debian, command: install
