### ISSUE TITLE
After last update

### ISSUE THREAD

**Issue by simpsss** [GameServerManagers/LinuxGSM#2898] opened 2020-05-21 13:32 UTC
## User Story

After last Linuxgsm update, Rust server dont update umod.

## Basic info

* **Distro:** [Ubuntu 18.04]
* **Game:** [Rust]
* **Command:** [rustserver mods-update]
* **LinuxGSM version:** [v20.3.0]

## Further Information

(23) Failed writing body
[ INFO ] Updating mods rustserver: Update addons/mods: 1 addons/mods will be updated
        * Oxide for Rust (overwrite)

==> Updating Oxide for Rust
clearing mod download directory /home/rustserver/lgsm/mods/tmp...OK
creating mod download directory /home/rustserver/lgsm/mods/tmp...OK
mkdir: cannot create directory ‘’: No such file or directory
fetching Oxide.Rust-linux.zip ...ERROR
mkdir: cannot create directory ‘’: No such file or directory
fetching  ...FAIL

**Comment by maikelpnl** [comment] 2020-05-21 13:44
same__

**Comment by dgibbs64** [comment] 2020-05-21 15:24
This will be going into a hotfix. The plan to release the hotfix today

**Comment by simpsss** [comment] 2020-05-22 20:23
LinuxGSM - Rust - Version v20.3.1

https://prnt.sc/sm01td

**Comment by dgibbs64** [comment] 2020-05-22 20:30
@simpsss looks like you might be having a dns issue as its failing to pull in LinuxGSM modules as well

**Comment by simpsss** [comment] 2020-05-22 20:34
Hi dgibbs,
I don't think it could be the DNS, because it updated others
See:

https://prnt.sc/sm07x7

**Comment by dgibbs64** [comment] 2020-05-22 21:56
Im not sure then as I have tested and its working fine for me

**Comment by h3o66** [comment] 2020-05-24 13:39
Fixed with release 20.3.1

**Closed by h3o66** 2020-05-24 13:39 UTC
Labels: command: mods, pr-merged

**Comment by SerKolomoets** [comment] 2020-05-28 12:15
Have same with CS:GO

### Basic info

    Distro: [Ubuntu 18.04]
    Game: [CS:GO]
    Command: [echo "metamod" | /home/csgoserver/csgoserver mods-install]
    LinuxGSM version: [v20.3.2]

### Further Information

```
Enter an addon/mod to install (or exit to abort): 
Installing MetaMod
=================================
creating LinuxGSM mods data directory /home/csgoserver/lgsm/mods...OK
creating mod download directory /home/csgoserver/lgsm/mods/tmp...OK
mkdir: cannot create directory '': No such file or directory
fetching mmsource-1.10.7-git971-linux.tar.gz ...ERROR
mkdir: cannot create directory '': No such file or directory
fetching  ...FAIL
```

**Comment by h3o66** [comment] 2020-05-28 15:48
@SerKolomoets please be sure that all functios of lgsm where updated.
I cannot reproduce this on my server

**Comment by dgibbs64** [comment] 2020-05-28 15:50
working for me as well

**Comment by SerKolomoets** [comment] 2020-05-28 18:58
@h3o66 Thank you, I'll check

**Comment by SerKolomoets** [comment] 2020-05-29 18:36
@h3o66 my bad, all working fine.
