### ISSUE TITLE
[FEATURE] Kill command

### ISSUE THREAD

**Issue by aStonedPenguin** [GameServerManagers/LinuxGSM#3499] opened 2021-07-01 21:16 UTC
## User Story
With game servers such as Garry's Mod a running the stop command disconnects all users before shutting down the server. This interferes with mods that allow clients to automatically reconnect when the server restarts. This has lead me to make a wrapper for lgsm that just kills the process whenever I run the stop command. This however does not tell lgsm the server has stopped and forces me to wait for lgsm to finish attempting to gracefully stop the server.

I would like a command to kill the servers process and mark the server as shutdown.

## Basic info

* **Distro:** n/a
* **Game:** All
* **Command:** [Kill]
* **LinuxGSM version:** n/a

## Further Information
There are of course less niche/hacky cases where the server is frozen and you'd just like to quickly kill the servers process and shut it down.

**Comment by Claiyc** [comment] 2021-07-01 21:37
You could also set the "stopmode" in the gmodserver.cfg to "1" (tmux kill).

**Comment by aStonedPenguin** [comment] 2021-07-01 21:49
> 
> 
> You could also set the "stopmode" in the gmodserver.cfg to "1" (tmux kill).

That solves my motivation but it would definitely still be useful.

**Comment by dgibbs64** [comment] 2021-07-07 12:31
Closing the issue as caused by a specific mod. By default, the stop command is used. The solution already exists to change stop type if a mod requires it.

**Closed by dgibbs64** 2021-07-07 12:31 UTC
Labels: type: feature request
