### ISSUE TITLE
Resolve Mods By ARK ( LGSM )

### ISSUE THREAD

**Issue by FlashModz** [GameServerManagers/LinuxGSM#1598] opened 2017-08-30 13:34 UTC
Hello Everyonne,

I found a solution for mods in ARK and that will avoid any errors.
Here is what I did. You can do the same with a symbolic links as needed.

Tested on Ubuntu 16.04 LTS

````bash
su YourUser
./arkserver stop
cd ./serverfiles/Engine/Binaries/ThirdParty/SteamCMD
mkdir ./Linux
cd ./Linux
curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
chown -R youruser:youruser ./ 
````

After 

````bash
cd ./lgsm/config-lgsm/arkserver
nano ./arkserver.cfg
````
and remplace the following content https://pastebin.com/70Pd6rkR

Save and close

After

````bash
cd /serverfiles/ShooterGame/Saved/Config/LinuxServer
nano ./GameUserSettings.ini
````

Add the following content
Put this last in your file GameUserSettings

````
[/Script/Game.ModInstaller]
ModIDS=680481868
ModIDS=682394267
ModIDS=714672786
````
Save and Close.

````cd
./arkserver start
````

Good Game For All 💃

**Comment by iskaraltok** [comment] 2017-08-31 17:52
Unfortunately this fix is not working for myself. Below is the postdetails and also what I see in the console for the server.

```Using binned.
4.5.1-0+UE4 7038 3077 402 7
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Redirecting stderr to '/home/arkserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Downloading item 731604991 ...
Success. Downloaded item 731604991 to "/home/arkserver/Steam/steamapps/workshop/content/346110/731604991" (46120351 bytes) ```


https://hastebin.com/upuhinuqok.sql

**Comment by Rayzos** [comment] 2017-09-04 12:58
This solution brings positive in the sense that the client sees the mod present on the server when the mod loaded on your client the server becomes invisible.

**Comment by UltimateByte** [comment] 2017-09-04 16:41
Thanks for the effort.
(I edited your post, edit it again to see how to enter code with the correct syntax :p )

**Comment by iskaraltok** [comment] 2017-09-04 19:42
Alright I have gotten this working now.

```
su YourUser
./arkserver stop
cd ./serverfiles/Engine/Binaries/ThirdParty/SteamCMD
mkdir ./Linux
cd ./Linux
curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
chown -R youruser:youruser ./ 
```
Then
```
cd ./lgsm/config-lgsm/arkserver
nano ./arkserver.cfg
```
and replace the following content https://pastebin.com/70Pd6rkR

Then
```
cd /serverfiles/ShooterGame/Saved/Config/LinuxServer
nano ./GameUserSettings.ini
```
Under [ServerSettings] add the following line like so, add ModIDS comma (,) separated:
```
[ServerSettings]
ActiveMods=<ModIDS>,<ModIDS>
```

Then symlink _steamapps_ to the above installed ~/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux
```
ln -s /home/arkserver/Steam/steamapps/ /home/arkserver/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps
```

**Comment by iskaraltok** [comment] 2017-09-04 20:26
Need also a solution for this, it seems like for each server it tries to download again even though they share the directories:
```
Downloading item 731604991 ...
Success. Downloaded item 731604991 to "/home/arkserver/Steam/steamapps/workshop/content/346110/731604991" (46120351 bytes) Downloading item 719928795 ...
Success. Downloaded item 719928795 to "/home/arkserver/Steam/steamapps/workshop/content/346110/719928795" (23826737 bytes) Downloading item 708807240 ...
Success. Downloaded item 708807240 to "/home/arkserver/Steam/steamapps/workshop/content/346110/708807240" (45742077 bytes) Downloading item 718412068 ...
Success. Downloaded item 718412068 to "/home/arkserver/Steam/steamapps/workshop/content/346110/718412068" (937015 bytes) CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 3 items discarded.
```

**Comment by Sdrabor** [comment] 2017-09-04 22:40
To add what I've noticed (very similarly to iskaraltok), here's what I did (Ubuntu 16.04 LTS):

I also did "
cd ./serverfiles/Engine/Binaries/ThirdParty/SteamCMD
mkdir ./Linux
cd ./Linux
curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
"
didn't have to chown since I ran the curl as my arkserver acct

deleted my ~/steamcmd and instead symlinked it via
ln -s /home/<user>/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/ /home/<user>/steamcmd

created where I wanted my mods to be downloaded
mkdir ~/mods

forced steamcmd to install one mod to force the install dir
~/steamcmd/steamcmd.sh +login anonymous +force_install_dir /home/arkserver/mods +workshop_download_item 346110 895711211

delete steamapps workshop dir if it exists
rm -R /home/<user>/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps/workshop

symlinked workshop to my mods dir via
ln -s /home/<user>/mods/steamapps/workshop/ /home/<user>/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps/workshop

also changed my arkserver.cfg to include (I'm running TheIsland map):
fn_parms(){
parms=""TheIsland?listen?MultiHome=${ip}?MaxPlayers=${maxplayers}?QueryPort=${queryport}?RCONPort=${rconport}?Port=${port}?" -automanagedmods"
}

**Comment by dgibbs64** [comment] 2017-09-10 19:44
This issue shoudl be resolved now. Please can this be confirmed then I will close

**Comment by RussianRonin** [comment] 2017-09-15 18:17
The incorrect directory seems to be symlinked with the ark fix.

My Postdetails: https://hastebin.com/itedemafix

So, the directory that is being symlinked now is arkserver/steamcmd to /home/russianronin/arkserver/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux

But the mods download to /home/russianronin/Steam/steamapps/workshop/content/346110/731604991 which I do not think the server has access to in any way.

If someone with a bit more experience with the linux ark server would like to confirm, it would be appreciated.

**Comment by iskaraltok** [comment] 2017-09-15 18:57
@RussianRonin I believe your issue is you didn't install it the suggested way under a new user called 'arkserver' you installed the ark server under your main user 'russianronin'

**Comment by RussianRonin** [comment] 2017-09-15 19:03
I get that.

But, even still, the script should take this into account. It makes it a lot easier to manage multiple servers under one user than one server under every user. I have not run into any other issues running this way before. And honestly, it should be an easy fix I would think?

**Comment by iskaraltok** [comment] 2017-09-15 19:06
@RussianRonin Yes but look at your directories, you have 1 extra level of hierarchy in your symlink

/home/**arkserver**/Steam/steamapps/ 
/home/**russianronin**/Steam/steamapps/

/home/**arkserver**/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps
/home/**russianronin/arkserver**/serverfiles/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps

**Comment by RussianRonin** [comment] 2017-09-15 19:13
Something like
```
ln -s "~/Steam/steamapps/" "${serverfiles}/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps"
```
would probably not be that hard to implement. Therefore it is relying on the home directory no matter what but still runs correctly to get the ${serverfiles} parameter.

**Comment by RussianRonin** [comment] 2017-09-16 04:10
After extensive testing, this is what I came up with.

You have to add
```
if [ ! -d "${serverfiles}/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps" ]; then
	ln -s "$HOME/Steam/steamapps/" "${serverfiles}/Engine/Binaries/ThirdParty/SteamCMD/Linux/steamapps"
fi
```
to fix_ark.sh

I did not do any manual modification except adding this to fix_ark.sh and clean installing ark and mods load flawlessly (of course after you do the proper mod setup for ark itself).

I am not the best at bash so I am sure someone has a better solution but this works for me flawlessly.

**Comment by RussianRonin** [comment] 2017-09-16 04:19
#1618

**Comment by dgibbs64** [comment] 2017-09-21 17:38
Please can the fix for this be confirmed as working and I will close this

**Comment by RussianRonin** [comment] 2017-09-21 17:43
I can confirm it is working but I would like other users confirmation as well!

**Comment by usud85** [comment] 2017-09-28 09:53
i always had another solution for updateing mods

ark checked every 10 minutes 
then ingame countdown when it will restart then download and update mods

**Comment by gamersalpha** [comment] 2017-10-12 18:46
Hello, @usud85 what is u other solution, he is interesting, can u share it please

**Comment by gamersalpha** [comment] 2017-11-02 08:31
Hello, 

up of this, can make it drectly on linuxGSM please

**Comment by gamersalpha** [comment] 2017-11-02 12:47
i foud this on my log : 

```
Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Downloading item 835113702 ...
Success. Downloaded item 835113702 to "/home/arkserver/Steam/steamapps/workshop/content/346110/835113702" (339523795 bytes) Downloading item 679529026 ...ERROR! Timeout downloading item 679529026depotreconstruct.cpp (1088) : Assertion Failed: m_nOutstandingWorkItems == 0
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 1 items discarded.
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 2 items discarded.
```

**Comment by gamersalpha** [comment] 2017-11-02 21:39
ok with the last release of linux-gsm, u don't have to do all this stuff, now mod are diretcly working with the linux-gsm last release

**Comment by shinji257** [comment] 2017-11-27 20:41
For this issue I ended up setting up arkserver.cfg.  The script does setup the majority of the things needed but you still need to add -automanagedmods.  This pastebin should do it.  Note that earlier pastebins or references missed needed escaping of quotes in the command line.  One version did work but it threw a spurious error that may or may not of affected things.

https://pastebin.com/MtSyPrWU

My actual extra params is a bit longer but that works on its own.  Once done you should end up with this.

`[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Redirecting stderr to '/home/arkserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Downloading item 558079412 ...
Success. Downloaded item 558079412 to "/home/arkserver/Steam/steamapps/workshop/content/346110/558079412" (2447056 bytes)
`

**Comment by gamersalpha** [comment] 2017-12-16 15:44
same bug here :/

i m stuck  can't make update mod and now i can't connect on my serveur :/

**Comment by gamersalpha** [comment] 2019-08-05 07:56
Hello, 

so i create a new server, and now same bug can't lunch mod on it :/

**Comment by gamersalpha** [comment] 2019-08-05 09:20
OK so what i do : 

1 - first frech install of linux gsm.

2 - adding my mod on this files like this : 

nano serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

ActiveMods=731604991,632091170,554678442

nano serverfiles/ShooterGame/Saved/Config/LinuxServer/Game.ini

[ModInstaller]
ModIDS=731604991
ModIDS=632091170
ModIDS=554678442


after that i restart my server : 

./arkserver restart


and when i ply o mod loading :/


so i try the command : 
./Arkserver debug andi have this : 

so something is wrong  :  

```
arkserver@srv-linux-01:~$ ./arkserver debug
[ INFO ] Debug arkserver: Check IP: 192.168.50.10

ARK: Survival Evolved Debug
=================================

Distro: Ubuntu 18.04.2 LTS
Arch:   x86_64
Kernel: 4.15.0-55-generic
Hostname:       srv-linux-01
tmux:   tmux 2.6
Avg Load:       1,04, 0,72, 0,53
Free Memory:    573MB
Free Disk:      203G
glibc required: 2.15
Server IP:      192.168.50.10:7777
Internet IP:    public7:7777
Master Server:  false

Start parameters:
./ShooterGameServer "TheIsland?AltSaveDirectoryName=TheIsland?listen?MultiHome=192.168.50.10?MaxPlayers=70?QueryPort=27015?RCONPort=27020?Port=7777 -automanagedmods"

Use for identifying server issues only!
Press CTRL+c to drop out of debug mode.
Warning! If arkserver is already running it will be stopped.

Continue? [Y/n] Y
[ INFO ] Debug arkserver: Stopping any running servers
[  OK  ] Stopping arkserver: Graceful: CTRL+c: 12: OK
[  OK  ] Debug arkserver: Starting debug
Using binned.
4.5.1-0+UE4 7038 3077 404 10
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/arkserver/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Downloading item 731604991 ...ERROR! Timeout downloading item 731604991CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.
```

and stuck here

someone get info please :

**Comment by dgibbs64** [comment] 2020-07-03 22:00
I completed a big overhaul of mods a couple of releases ago so mods should be working much better now

**Closed by dgibbs64** 2020-07-03 22:00 UTC
Labels: type: bug, game: ARK: Survival Evolved, engine: unreal4
