### ISSUE TITLE
EasyAntiCheat Server Shutting Down

### ISSUE THREAD

**Issue by Nark0t1k** [GameServerManagers/LinuxGSM#2497] opened 2019-09-05 20:34 UTC
![image](https://user-images.githubusercontent.com/7716208/64378518-2ab32500-d02d-11e9-9abc-c6ce057449ec.png)

**User Story**
When i start rust server it's close himself with 
"EasyAntiCheat Server Shutting Down"
The error look like the same : https://github.com/GameServerManagers/LinuxGSM/issues/1813

**Basic info**
Distro: Debian 9
Game: Rust
Command: ./rustserver start
Further Information
Since the last update that didn't work anymore.

**To Reproduce**
Download the last rust update (https://steamcommunity.com/games/252490/announcements/detail/1603766940169762196)
Run rust server with
run ./rustserver start

**Comment by maks2204** [comment] 2019-09-05 22:16
I have the same problem!

**Comment by lukespragg** [comment] 2019-09-06 17:18
This is caused by downloading the Windows build of Oxide. LGSM would need to be updated to use the Linux build, which is currently found at https://umod.org/games/rust/download/develop.

**Comment by Frisasky** [comment] 2019-09-07 04:55
since underlying cause of the problem is oxide update, so i'd gonna close this issue so discussion could be concentrated on this thread
https://github.com/GameServerManagers/LinuxGSM/issues/2498

**Closed by Frisasky** 2019-09-07 04:55 UTC
Labels: type: bug
