### ISSUE TITLE
Weird Problem with tmux sessions?

### ISSUE THREAD

**Issue by robingroppe** [GameServerManagers/LinuxGSM#561] opened 2015-12-18 05:11 UTC
Hey i ran into a problem yesterday.
I have one user and in the homedir is a csgoserver and a insserver folder with the lsgm in it.
I can start both the server alone just fine. But when i try to start both it is not working.
When the csgoserver is running and i try to start insserver it tells me that the session ins-server cannot be found. 
When insserver is running and i want to start csgoserver it tells me that the server is already running but in fact insserver is the only thing running. 

Ubuntu Trusty, tried with distro tmux and backported 1.9.8 neither works.

**Comment by UltimateByte** [comment] 2015-12-18 12:56
Hi,

Did you make one user per server as expected ?

**Comment by robingroppe** [comment] 2015-12-18 13:01
Nope, I got only one user for the gameservers.
I prevously had a larger gameserver with 4-6 lgsm instances with one user and it worked fine.
Why should that be a problem? The session-name is different.

**Comment by UltimateByte** [comment] 2015-12-18 13:29
As far as i know, it's very recommended to make one user per server.
It's not  only a LGSM recommandation, it's also a global linux recommandation.
I don't know if you're new to linux, i'm only into it since like 2 years, but at the beginning, i thought it was boring to make a new user every single time... But in the end, it makes things so easier to diagnose when you have a problem, like when you wanna see what's running from a user, or kill a user's process... 
Then with this script, you can use a root crontab to monitor/reboot all users' servers in one place. 

BTW, it still seems weird.
If somebody has enough knowledge to understand them, here are the suspected responsible lines.

https://github.com/dgibbs64/linuxgsm/blob/master/functions/fn_start#L143
tmuxwc=$(tmux list-sessions 2>&1|awk '{print $1}'|grep -Ec "^${servicename}:")

https://github.com/dgibbs64/linuxgsm/blob/master/functions/fn_start#L117
if [ "${tmuxwc}" -eq 1 ]; then
	fn_printinfo "${servername} is already running"
	fn_scriptlog "${servername} is already running"
	sleep 1
	echo -en "\n"
	exit
fi

**Comment by robingroppe** [comment] 2015-12-18 13:43
Actually I am not new to linux. I use it every day on my deskop and on my servers.
I know that that the general recommendations suggest using one user per service, mostly due to security reasons. 
But I think for a few gameservers I dont need multiple users.
Earlier this year it has worked flawlessly and I dont know why its not working anymore.

**Comment by dgibbs64** [comment] 2015-12-18 17:21
It is recommended to use separate users for the reasons @UltimateByte suggested. However it isnt required. for example /home/lgsm should work fine. 

tmuxwc variable gives the number of active sessions running the same session name. For example if there is already a session called ins-server it will state its already running. This stops accidentally starting the server multiple times. The only way it will state its already running if ins-server session is active. I would re download csgoserver and insserver again and try then. Maybe check that all tmux sessions are killed and processess ended.

The outputs of ./csgoserver details and ./insserver details may give use more useful info

**Comment by robingroppe** [comment] 2015-12-18 17:28
I dont think so. I killed all tmux sessions prevously.
I can only give information about csgo atm as I purged the insserver install to reinstall it later.
I will let you know how it went.

csgo:
https://www.zerobin.tk/?bb3e862d72f2d8be#Q8O5voXsMzbAJ0eKDESddbOIeyIl+V7218KyBnyk4Og=

**Comment by dgibbs64** [comment] 2015-12-18 18:28
@robingroppe I cannot see anything odd in your details. Here hopfully a fresh install of ins-server helps

**Comment by robingroppe** [comment] 2015-12-23 11:31
Okay, the story goes on. 
Now I am trying to set up a second csgo server.
Both can be started seperately but if one in running and i want to start the second one, it is starting and killing the first one.
Something is really wrong here.

**Comment by robingroppe** [comment] 2015-12-23 11:58
I got both of them running now by changing the session name of the second server to "casual" instead of "csgo-server-casu". 
So there is only a problem if the first session is "csgo-server" and the second "csgo-server-casu".

**Comment by UltimateByte** [comment] 2015-12-23 22:04
Seems like the script or tmux can't make the difference between names like XXX-YY and XXX-ZZ.

**Comment by jaredballou** [comment] 2016-01-06 05:21
Is the service name a factor here? I had problems with symlinked scripts blowing up when I didn;t tie the servicename variable to the name of the symlink. Would you mind putting up your modified server scripts for us to review?

**Comment by UltimateByte** [comment] 2016-01-06 13:08
2 identical service names cause the issue. I've been experiencing this not long ago.
I'm gonna try making 2 gmodservers in the same user and see what happens while messing up with service names.

**Comment by UltimateByte** [comment] 2016-01-06 13:46
Well, just tried with gmod servers on the same user.

If i set 
Server 1) servicename="gmod-server1" 
Server 2) servicename="gmod-server2"
Then start both, they both work correctly, but the 2 displays UNAVAILABLE instead of the servername at start/stop commands.

So i tried inverting the service names : 
Server 1) servicename="gmod-server2" 
Server 2) servicename="gmod-server1"
Then it's server one that displays errors. 

So i tried whole different names : 
Server 1) servicename="gmodserver1" 
Server 2) servicename="gmodserver2"
Then both display UNAVAILABLE at start, but work as intended.

@dgibbs64 
So there is actually a problem in the way servicename is managed.

**Comment by robingroppe** [comment] 2016-01-06 13:59
This is a regession. About one year ago I installed a set of csgo servers.
One named csgo-server-comp and the other csgo-server-casu and it worked
perfectly. something must have been changes in the way service names are
handled.
Am 06.01.2016 14:46 schrieb "UltimateByte" <notifications@github.com>:

**Comment by UltimateByte** [comment] 2016-01-06 14:58
Well, i'm pretty sure it's related to fn_start_tmux, but i have to admitt my knowledge isn't good enough yet to understand how it really works and why it could fail.
https://github.com/dgibbs64/linuxgsm/blob/master/functions/command_start.sh#L74
I won't be able to help anymore with that one any time soon.

**Comment by dgibbs64** [comment] 2016-01-06 19:36
It stated UNAVAILABLE if LGSM cannot see the config file. I will have to try to add a check to warn if the config file is not accessable

**Comment by robingroppe** [comment] 2016-01-06 19:43
Yes but thats only the result of lgsm not knowing what session the command is about.
As I said, weid things happen when messing around with these things. I saw the unavailable too.
I have not investigated this problem yet. 
Do you recall commiting any changes to the way lsgm handles the sessions? @dgibbs

**Comment by UltimateByte** [comment] 2016-01-06 20:01
OK thangs dgibbs64, so that's due to the fact that if you change servicename, you have to change server config name too.
Example : Using servicename="blabla", you should rename "gmod-server.cfg" to "blabla.cfg"
Or, better way in my opinion :  change servercfg="${servicename}.cfg" to servercfg="gmod-server.cfg".

**Comment by dgibbs64** [comment] 2016-01-06 20:37
Added a new check https://github.com/dgibbs64/linuxgsm/pull/611
Please test and see if this helps.

I may add the option to download a default config however that may confuse the user if they miss the warning as downloading the default config would cause the message to stop

**Comment by dgibbs64** [comment] 2016-01-06 20:39
@robingroppe I don't think I have changed how sessions work for a long time

**Comment by JimTR** [comment] 2016-01-06 20:47
I test if servicename.cfg exists if not use lsgm-default.cfg

**Comment by robingroppe** [comment] 2016-01-06 21:09
Absolutely correct. 
1. /home/user/server1/whateverserver
2. /home/user/server2/whateverserver 
Where server1 and 2 are the servicenames.
Server one and two alone are running fine but both server at once is not working because both have the word "server" in the servicename. I just confirmed that by setting one servicename to "somethingdifferent".
And both servers work as expected.

**Comment by JimTR** [comment] 2016-01-06 21:36
nope incorrect just add something to the end of the service name ... you then get tmux sessions like 
![likeso](https://cloud.githubusercontent.com/assets/4038510/12155441/f8b8925e-b4bc-11e5-84e9-0a42182240c0.png)
 so  you could install at /home/user/games/gamename
copy the executable eg cgso-server to cgso-server1 .. edit cgso-server1 so the ports are different & the service name is different then make sure you have cfg files that match the service name

**Comment by robingroppe** [comment] 2016-01-06 22:09
Exactly that is not working for me.

csgo-server-1
csgo-server-2
.
.
.

Are you using recent function files?

**Comment by JimTR** [comment] 2016-01-06 22:12
what is the result if you run 'tmux ls' in a terminal ?

**Comment by robingroppe** [comment] 2016-01-06 22:36
https://www.zerobin.tk/?af6e6fc568e1a800#iPowQg8bFBKH9KxiL4IkAduPCzMQKvXdCzUB6gZ3e0Y=

**Comment by robingroppe** [comment] 2016-01-06 22:38
As you can see, I start the first one, then the second one.
After doing that only the second one is running.

**Comment by JimTR** [comment] 2016-01-06 22:58
so I just don't get this are you sure that both service names are different  why not 'tmux ls' after the start of the first server (note the session) then start the second ? from the screen shot provided it is difficult to work out what has gone on with session 1

**Comment by robingroppe** [comment] 2016-01-06 23:43
https://www.zerobin.tk/?8e765aa5b18952a5#CWyt0GuLSXMGM2MAReS1TWCN3ugZJLAhkOZ40NaUFo4=

**Comment by robingroppe** [comment] 2016-01-06 23:51
https://www.zerobin.tk/?b52604f38ee09c67#qjqE0PTcI0P5+eBYD1GyLKGYEvaxJSQZNEcL4FMQ/iY=

**Comment by JimTR** [comment] 2016-01-06 23:54
That sort of indicates there is something wrong with your server setup .. unless you are going to tell me that server1 runs for weeks ... then I add server2 & it fails .... to be fair I would delete both server installs & start again ... do server install get that one running fine (test it for a while) then copy the executable so 'cp server server2 ' edit server2 to reflect the new ports (note you will have to change all 3) and change the service name just a thought what version of linux does your machine use ?

**Comment by robingroppe** [comment] 2016-01-06 23:59
My server setup is fine.
I replicated it in a virtual machine a few days ago.
Server one is absolutely reliable. 
What you described is exactly what i have done a few hours ago.
Still Ubuntu Trusty ;) And I have tested with the distro tmux version and with a newer backported version.

**Comment by JimTR** [comment] 2016-01-07 00:19
you miss the point ... when I refer to server I mean the game server(s) I have no doubt that your server is running fine hence why I said just remove the games servers & start again. I have 56 servers running across about 8 unix users and don't get the issue using ubuntu 14.04 server so I guess there is a game server issue

**Comment by robingroppe** [comment] 2016-01-07 01:31
On Insurgency and Counter-Strike?

**Comment by JimTR** [comment] 2016-01-07 03:01
if you looked at the image you would see 1 Cs a few Gmod a No More Room In Hell etc ... the screen shot was from 1 user tbf I could not (unless I looked) tell you what else is running across the other users all run with no issue @robingroppe  you have the issue I am trying to help you fix it

**Comment by robingroppe** [comment] 2016-01-07 10:03
Okay. I used to run a comparable set of gameservers which i install a year a go or so without any problems.
Is this problem confirmed by anyone or am I the only one with this issue?
@UltimateByte ?

**Comment by UltimateByte** [comment] 2016-01-07 13:48
I personally tried 2 things : 

1 user, 2 separate folders, 2 different servicenames : gmod-server1 and gmod-server2.
=> As long as i've got one .cfg file per server that is the same name as servicename, it runs fine.

1 user, 1 folder, 2 different scripts with different servicenames and corresponding .cfg files
=> Works fine too.

Output : 
serverdev@lrob:~/gmodserver1$ ./gmodserver start
[  OK  ] Starting gmod-server1: whatever
serverdev@lrob:~/gmodserver1$ ./gmodserver2 start
[  OK  ] Starting gmod-server2: whatever2 test serv
serverdev@lrob:~/gmodserver1$ tmux ls
gmod-server1: 1 windows (created Thu Jan  7 14:51:28 2016) [105x48]
gmod-server2: 1 windows (created Thu Jan  7 14:51:38 2016) [105x48]
serverdev@lrob:~/gmodserver1$

I first messed up with script session names before getting it working though. So be careful, and then i see no reason why it wouldn't work.
As a reminder, i'm using Debian 8.2

**Comment by robingroppe** [comment] 2016-01-07 13:58
Okay then probably I messed it up serval times.
Sorry.

**Comment by UltimateByte** [comment] 2016-01-07 14:06
Please, keep us informed.
I leave that opened for a few days maximum or until you tell us you got it working. :)

**Comment by UltimateByte** [comment] 2016-01-23 09:42
As i coudln't reproduce the issue and no update for the OP, closing this.
Feel free to re-open if needed.

**Closed by UltimateByte** 2016-01-23 09:42 UTC
Labels: distro: Ubuntu, distro: Debian, game: Counter-Strike: Global Offensive, engine: source, game: Insurgency
